[AGM-1114] AdGuard Safari Web extension
AdguardTeam/AdguardKnowledgeBase pull request #1001
Opened 2021-12-10 16:57 UTC by vbagirov

No screenshots yet

2021-12-10 17:11 UTC, ameshkov commented on 05.ios/04.safari-web-extension/docs.en.md
> +title: 'AdGuard Safari Web Extension'
"Web Extension"

In the text:

AdGuard's Safari [Web extension](https://developer.apple.com/documentation/safariservices/safari_web_extensions)

2021-12-10 17:16 UTC, ameshkov commented on 05.ios/04.safari-web-extension/docs.en.md
> +
Add the extension's main popup screenshot

2021-12-13 11:42 UTC, anastasiia-fedotova commented on 05.ios/04.safari-web-extension/docs.ru.md
> +По умолчанию, Safari предоставляет блокировщикам контента только базовые инструменты. Эти инструменты не позволяют добиться уровня блокировки, который присущ блокировщикам на других операционных сист
скорее не "присущ", а "доступен"

такие мощные оружия -> такие мощные средства против рекламы (ну, или как-то ещё, но не оружия точно)

2021-12-13 11:45 UTC, anastasiia-fedotova commented on 05.ios/04.safari-web-extension/docs.ru.md
> +* **Включение/выключение защиты на текущем сайте**. Сдвиньте переключатель в положение "выкл.", чтобы полностью отключить работу AdGuard на текущем сайте и добавить соответствующее правило-исключение
я бы сказала "повторное нажатие на переключатель" или "повторный клик по переключателю"

2021-12-13 11:48 UTC, anastasiia-fedotova commented on 05.ios/04.safari-web-extension/docs.ru.md
> +После того, как это сделано, откройте раздел *Настройки > Safari > Расширения*. Найдите раздел **Разрешите эти расширения** и затем найдите **AdGuard** среди доступных расширений. Нажмите на него и в
После того, как это сделано - звучит калькой с английского. Я бы заменила на "Затем"

2021-12-13 11:52 UTC, anastasiia-fedotova commented on 05.ios/04.safari-web-extension/docs.ru.md
> +После того, как это сделано, откройте раздел *Настройки > Safari > Расширения*. Найдите раздел **Разрешите эти расширения** и затем найдите **AdGuard** среди доступных расширений. Нажмите на него и в
После запуска AdGuard для iOS откройте раздел *Настройки > Safari > Расширения*. Найдите раздел **Разрешите эти расширения** и затем выберите **AdGuard** среди доступных расширений.

2021-12-13 11:56 UTC, anastasiia-fedotova commented on 05.ios/04.safari-web-extension/docs.en.md
> +By default, Safari provides only basic tools to content blockers. These tools don't allow the level of performance that can be found in content blockers on other operating systems (Windows, Mac, Andr
А почему в ру версии нет предложения про рекламу в ютубе?

2021-12-13 12:36 UTC, ameshkov requested changes

2021-12-13 13:13 UTC, ameshkov requested changes

2021-12-13 13:13 UTC, ameshkov commented on 05.ios/04.safari-web-extension/docs.en.md
> +![](https://cdn.adguard.com/public/Adguard/kb/iOS/webext/menu_en.jpeg)
1. Please use light theme everywhere
2. The screenshot should not be expanded

2021-12-13 13:13 UTC, ameshkov commented on 05.ios/04.safari-web-extension/docs.en.md
> +![](https://cdn.adguard.com/public/Adguard/kb/iOS/webext/menu_en.jpeg)
Reduce the screenshots size (width=600 would be enough)

2021-12-13 15:20 UTC, ameshkov approved these changes

2021-12-13 15:21 UTC, merged