Agm 938 vpn kb update some fixes
AdguardTeam/AdguardKnowledgeBase pull request #1002
Opened 2021-12-13 08:18 UTC by anastasiia-fedotova

Replaced placeholders with links

2022-03-22 11:04 UTC, el-termikael requested changes

2022-03-22 11:04 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/030.integrated-mode/docs.ru.md
> +В приложении AdGuard VPN по умолчанию включен Основной режим работы, при котором используется собственный [протокол AdGuard VPN](https://kb.adguard.com/ru/vpn/adguard-vpn-general/how-adguard-vpn-prot
В AdGuard VPN есть два режима работы — Основной и Интегрированный. Основной включен по умолчанию, при нём используется [протокол AdGuard VPN](https://kb.adguard.com/ru/vpn/adguard-vpn-general/how-adguard-vpn-protocol-works). Этот режим — лучшая комбинация скорости и безопасности соединения, но он не позволяет одновременно использовать AdGuard VPN и блокировщик рекламы AdGuard. В Интегрированном режиме используется протокол IPSec, при котором возможна совместная работа приложений AdGuard. Если у вас уже есть блокировщик AdGuard и вы решили установить AdGuard VPN, Интегрированный режим включится автоматически и позволит вам пользоваться двуми приложениями одновременно. Если же сначала вы установили AdGuard VPN, а уже потом решили попробовать блокировщик AdGuard, то, чтобы пользоваться ими одновременно, выполните следующие действия:

2022-03-22 11:04 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/030.integrated-mode/docs.ru.md
>  1. Откройте приложение AdGuard VPN для iOS и выберите "Настройки" в правом нижнем углу экрана.
по-хорошему кавычки бы ещё на ёлочки поменять, но это не критично

2022-03-22 11:04 UTC, el-termikael commented on 11.vpn/060.vpn-browser-extensions/010.overview/docs.ru.md
> +[Подписка](https://adguard-vpn.com/ru/license.html) позволяет пользоваться AdGuard VPN без ограничений по трафику, скорости и количеству доступных локаций. Ещё одно преимущество в количестве устройст
Ещё одно преимущество в количестве устройств, на которых можно одновременно использовать AdGuard VPN с одного аккаунта – в бесплатной версии их всего два, а в платной пять.
—>
Ещё одно преимущество — в количестве устройств, на которых можно одновременно использовать AdGuard VPN с одного аккаунта: в бесплатной версии их всего два, а в платной пять.

2022-03-23 14:17 UTC, el-termikael requested changes

2022-03-23 14:17 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +AdGuard VPN also has its own [*protocol*](https://kb.adguard.com/en/vpn/adguard-vpn-general/how-adguard-vpn-works). One of its advantages is that the traffic transmitted using the AdGuard VPN protoco
тут была правка про usual traffic, потерялась, кажется

2022-03-23 14:47 UTC, el-termikael approved these changes

2022-06-07 11:59 UTC, vbagirov commented
Too many conflicts, the changes were made directly to the VPN KB.

2022-06-07 11:59 UTC, closed without merging