New article solving problems
AdguardTeam/AdguardKnowledgeBase pull request #1006
Opened 2021-12-15 14:29 UTC by anastasiia-fedotova

New article How to protect AdGuard VPN from being disabled by the system.

2021-12-15 15:00 UTC, vbagirov requested changes

2021-12-15 15:00 UTC, vbagirov commented on 11.vpn/020.adguard-vpn-for-android/030.solving-problems/010.background-work/docs.en.md
> +In some cases, apps cannot stay in the background ("alive" or in a sleep mode) due to Android OS optimization function, or so-called "battery save mode" — this feature can kill background application
1) Inconvenience -> всё хуже, приложение просто перестаёт работать, когда система его убивает
2) Не везде это последний шаг, надо просто сказать что "подставляйте везде AdGuard VPN вместо AdGuard"

2021-12-15 15:00 UTC, vbagirov commented on 11.vpn/020.adguard-vpn-for-android/030.solving-problems/010.background-work/docs.en.md
> +In some cases, apps cannot stay in the background ("alive" or in a sleep mode) due to Android OS optimization function, or so-called "battery save mode" — this feature can kill background application
Для ру аналогично

2022-03-22 10:01 UTC, el-termikael requested changes

2022-03-22 10:01 UTC, el-termikael commented on 11.vpn/020.adguard-vpn-for-android/030.solving-problems/010.background-work/docs.ru.md
> +Если работа AdGuard VPN на вашем устройстве будет остановлена, ваши персональные данные окажутся под угрозой. Чтобы избежать подобной проблемы, вам нужно перейти по [этой ссылке](https://kb.adguard.c
Чтобы избежать подобной проблемы, перейдите [по этой ссылке](https://kb.adguard.com/ru/android/solving-problems/background-work) и следуйте инструкции для вашего устройства с одной лишь разницей: везде, где это требуется, выбирайте AdGuard VPN вместо AdGuard.

2022-03-22 10:05 UTC, el-termikael requested changes

2022-03-22 16:15 UTC, el-termikael requested changes

2022-03-22 16:15 UTC, el-termikael commented on 11.vpn/020.adguard-vpn-for-android/030.solving-problems/010.background-work/docs.en.md
> +Apps on Android devices may not always run and stay in the background for various reasons. This is most often due to Android OS optimization function, or so called "battery save mode". In such cases,
а зачем stay in the background? run in the background вроде достаточно

2022-03-22 16:15 UTC, el-termikael commented on 11.vpn/020.adguard-vpn-for-android/030.solving-problems/010.background-work/docs.en.md
> +Apps on Android devices may not always run and stay in the background for various reasons. This is most often due to Android OS optimization function, or so called "battery save mode". In such cases,
короче and stay всё ещё лишнее

2022-03-22 16:15 UTC, el-termikael commented on 11.vpn/020.adguard-vpn-for-android/030.solving-problems/010.background-work/docs.ru.md
> +Приложения на устройствах Android не всегда могут работать и оставаться в фоновом режиме по разным причинам. Чаще всего это происходит из-за встроенной функции оптимизации операционной системы Androi
работать и оставаться в фоновом режиме —>  работать в фоновом режиме

2022-03-23 11:43 UTC, el-termikael approved these changes

2022-03-23 11:48 UTC, merged