Removed info about bypassing geo-restrictions
AdguardTeam/AdguardKnowledgeBase pull request #1024
Opened 2022-02-01 09:34 UTC by anastasiia-fedotova

2022-02-01 11:23 UTC, vbagirov requested changes

2022-02-01 11:23 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/020.adguard-vpn-is-the-better-option/docs.en.md
> +Streaming services don't like VPNs for obvious reasons: according to statistics, about 20% of users install a VPN it mainly to watch shows, TV shows and movies bypassing geo-blocking. That's why stre
я думаю проще этот пункт вообще убрать

2022-02-02 12:48 UTC, anastasiia-fedotova commented on 11.vpn/010.adguard-vpn-general/020.adguard-vpn-is-the-better-option/docs.en.md
> +Streaming services don't like VPNs for obvious reasons: according to statistics, about 20% of users install a VPN it mainly to watch shows, TV shows and movies bypassing geo-blocking. That's why stre
Дэн одобрил такой вариант (без перечисления сервисов):

## 11. Secure streaming

Streaming services don't like VPNs for obvious reasons: according to statistics, about 20% of users install a VPN mainly to watch shows, TV shows and movies bypassing geo-blocking. That's why streaming platforms tend to do everything they can to track VPN traffic and block it.

But what if you want to watch content specific to your region while feeling safe? Or don't want stop watchig exciting series even when you travel to another country?The answer is simple — AdGuard VPN.

2022-02-02 12:52 UTC, vbagirov requested changes

2022-02-02 12:52 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/020.adguard-vpn-is-the-better-option/docs.en.md
> +Streaming services don't like VPNs for obvious reasons: according to statistics, about 20% of users install a VPN it mainly to watch shows, TV shows and movies bypassing geo-blocking. That's why stre
Ну надо тогда подчеркнуть что типа стриминги блочат впны, но с адичем типа всё збс, только не используйте его в нелегальных целях

2022-02-02 13:06 UTC, anastasiia-fedotova commented on 11.vpn/010.adguard-vpn-general/020.adguard-vpn-is-the-better-option/docs.en.md
> +Streaming services don't like VPNs for obvious reasons: according to statistics, about 20% of users install a VPN it mainly to watch shows, TV shows and movies bypassing geo-blocking. That's why stre
But what if you want to watch content specific to your region while feeling safe? Or don't want stop watchig exciting series even when you travel to another country? The answer is simple — AdGuard VPN, which thanks to its unique protocol can remain invisible to services. 

> Before you start watching a show on a streaming service with a VPN enabled, make sure you have a subscription and your actions are legal.

2022-02-03 09:40 UTC, vbagirov approved these changes

2022-02-03 11:38 UTC, merged