Update $domain modifier description
AdguardTeam/AdguardKnowledgeBase pull request #1035
Opened 2022-03-01 15:22 UTC by maximtop

This pr fixes #1018

2022-03-01 18:08 UTC, ameshkov approved these changes

2022-03-02 00:01 UTC, nataMai requested changes

2022-03-02 00:01 UTC, nataMai commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +To perform a target domain matching the following predicate for the conditions should be satisfied: `1 AND ((2 AND 3) OR 4)`. That is, in case the `$domain` modifier contains only excluded domains, t
```suggestion
The following predicate should be satisfied to perform a target domain matching: `1 AND ((2 AND 3) OR 4)`. That is, if the modifier `$domain`  contains only excluded domains, then the rule does not need to meet the second and third conditions to match the target domain against the modifier `$domain`.
```

2022-03-02 08:04 UTC, maximtop commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +To perform a target domain matching the following predicate for the conditions should be satisfied: `1 AND ((2 AND 3) OR 4)`. That is, in case the `$domain` modifier contains only excluded domains, t
Added suggestion

2022-03-02 18:01 UTC, merged