Grammar updates to the General folder
AdguardTeam/AdguardKnowledgeBase pull request #1040
Opened 2022-03-15 16:06 UTC by nataMai

2022-03-17 17:12 UTC, vbagirov requested changes

2022-03-17 17:12 UTC, vbagirov commented on 01.general/14.filter-rules-statistics/docs.en.md
> +They are manually compiled based on your complaints about ads on websites. Ad filters are one of the most important elements of AdGuard - their quality determines the overall quality of AdGuard ad bl
one of the most - some of the most? или можно и так?

2022-03-17 17:12 UTC, vbagirov commented on 01.general/14.filter-rules-statistics/docs.en.md
> +However, there is a downside. Over the years, more and more ad filters have appeared. And the more ad filters are there, the more memory AdGuard consumes, thus slowing down the rendering of web pages
если more and more то наверное имеется в виду процесс и должно быть have been appearing?

2022-03-17 21:07 UTC, nataMai commented on 01.general/05.adguard-filter-policy/docs.en.md
> +- CSS and JS injection rules should be used as rarely as possible and only when it is impossible to block ads without them.
Will - это когда просто будут и всё, без условий.
Shall - должествование близкое к MUST. 
Should - долженствование более мягкое. 
Вот полезный ресурс по [RFC](https://www.ietf.org/rfc/rfc2119.txt) 

Я вижу, что тут лучше более мягкое должествование-пожелание should, потому как нечеткое условие as rarely as possible.

2022-03-17 21:13 UTC, nataMai commented on 01.general/07.how-ad-blocking-works/docs.en.md
> +Basically, all AdGuard ad blocker products can block web requests according to the active filter rules. This method is very effective at stopping the ad, but it has some drawbacks. The most obvious o
Updated

2022-03-17 21:19 UTC, nataMai commented on 01.general/09.license-key/docs.en.md
> +An AdGuard account allows you to manage your license keys and their binding to your devices.
Исправила на 
An AdGuard account allows you to manage your license keys, their binding to your devices, and your purchase history.

2022-03-17 22:20 UTC, nataMai commented on 01.general/10.why-is-adguard-better/docs.en.md
> +Apart from blocking ads, AdGuard gives you a lot of additional tools. Perhaps the most important of them is our Phishing Site Filter. This module uses a constantly updated database of malicious and p
Updated

2022-03-17 22:28 UTC, nataMai commented on 01.general/12.search-ads-and-self-promotion/docs.en.md
> +**Declaration.** While AdGuard provides an option to show some ads, we do not have any 'acceptable ads' program like Adblock Plus and some other ad blockers, where they take money for leaving certain
Disclamer обычно означает "негатив", сужение ответственности за что-то. По смыслу это - "мы не совсем отвечаем за это, за это отвечает кто-то еще, поэтому никаких к нам претензий, do it at your own risk".
Тут же наоборот - мы расширяем и обозначаем свою позицию.
Так что тут Disclamer не подходит.  Manifest показался мне слишком претенциозным. 
Если не нравится Declaration, то могу еще предложить Disclosure.

2022-03-17 22:30 UTC, nataMai commented on 01.general/13.adguard-beta-testing-program/docs.en.md
> +* Find us on various social media platforms, like [Facebook],(https://www.facebook.com/AdguardEn/), [Reddit](https://www.reddit.com/r/Adguard/), etc. However, this is not the most convenient way to d
Updated

2022-03-17 22:34 UTC, nataMai commented on 01.general/14.filter-rules-statistics/docs.en.md
> +They are manually compiled based on your complaints about ads on websites. Ad filters are one of the most important elements of AdGuard - their quality determines the overall quality of AdGuard ad bl
Можно и так, и сяк. Предлагаю заменить на почетче:
Ad filters are an essential element of AdGuardю

2022-03-17 22:43 UTC, nataMai commented on 01.general/14.filter-rules-statistics/docs.en.md
> +However, there is a downside. Over the years, more and more ad filters have appeared. And the more ad filters are there, the more memory AdGuard consumes, thus slowing down the rendering of web pages
Если имеем в виду процесс, то да. А если сказать чуть проще? 
The amount of ad filters is growing every day.
Every day, there are more and more ad filters.

2022-03-17 22:45 UTC, nataMai commented on 01.general/15.dns-filtering/docs.en.md
> +There are thousands of DNS servers to choose from, and they are all unique in their properties and purposes. Most of them simply return the IP address of the requested domain, but some have additiona
Updated

2022-03-18 08:47 UTC, vbagirov commented on 01.general/12.search-ads-and-self-promotion/docs.en.md
> +**Declaration.** While AdGuard provides an option to show some ads, we do not have any 'acceptable ads' program like Adblock Plus and some other ad blockers, where they take money for leaving certain
Declaration кажется каким-то слишком пафосным, примерно как Manifest. Давай Disclosure сделаем наверное

2022-03-18 08:48 UTC, vbagirov commented on 01.general/14.filter-rules-statistics/docs.en.md
> +They are manually compiled based on your complaints about ads on websites. Ad filters are one of the most important elements of AdGuard - their quality determines the overall quality of AdGuard ad bl
можно так, да

2022-03-18 08:49 UTC, vbagirov commented on 01.general/14.filter-rules-statistics/docs.en.md
> +However, there is a downside. Over the years, more and more ad filters have appeared. And the more ad filters are there, the more memory AdGuard consumes, thus slowing down the rendering of web pages
Ну не, всё же не каждый день мы добавляем новые. Либо have been appearing, либо написать в духе "регулярно появляются новые" и т.п.

2022-03-18 22:47 UTC, nataMai commented on 01.general/14.filter-rules-statistics/docs.en.md
> +However, there is a downside. Over the years, more and more ad filters have appeared. And the more ad filters are there, the more memory AdGuard consumes, thus slowing down the rendering of web pages
Updated

2022-03-18 22:56 UTC, nataMai commented on 01.general/12.search-ads-and-self-promotion/docs.en.md
> +**Declaration.** While AdGuard provides an option to show some ads, we do not have any 'acceptable ads' program like Adblock Plus and some other ad blockers, where they take money for leaving certain
Updated.

2022-03-18 22:58 UTC, nataMai commented on 01.general/11.https-filtering/docs.en.md
> +Most of the problems discovered in the above study are related to certificate validation mechanisms. This is what we want to focus on first. We are working on a separate certificate validation librar
It is fine.

2022-03-19 02:18 UTC, nataMai commented on 01.general/11.https-filtering/docs.en.md
> +The thing is, as more and more websites, blogs, social media, and others switch to HTTPS, more ad networks follow them to HTTPS as well, because it becomes necessary to display ads on HTTPS-based web
Updated.

2022-03-19 02:22 UTC, nataMai commented on 01.general/11.https-filtering/docs.en.md
> +By default, AdGuard doesn’t filter any information on websites of banks, payment systems, or websites with valuable personal data. We maintain a list of more than [1,300 such exclusions](https://gith
Updated

2022-03-19 02:24 UTC, nataMai reviewed
I've added updates as per your suggestions. All conversations should be resolved.

2022-03-22 15:11 UTC, vbagirov submitted a review, later dismissed

2022-03-22 15:20 UTC, merged