Add $hls modifier descriptions
AdguardTeam/AdguardKnowledgeBase pull request #1085
Opened 2022-06-29 15:50 UTC by ngorskikh

2022-06-29 17:01 UTC, slavaleleka commented
хорошо бы ещё про совместимость написать

2022-07-03 18:59 UTC, ameshkov requested changes

2022-07-03 18:59 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +#### **`$hls`**
We need a disclaimer that these rules are only supported in the versions of AdGuard that use CoreLibs 1.10 or newer (i.e. nightlies for now)

2022-07-11 12:32 UTC, el-termikael submitted a review, later dismissed

2022-07-11 13:10 UTC, ameshkov submitted a review, later dismissed

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +`$hls` правила модифицирует ответ на соответствующий правилу запрос. Они предназначены для удаления сегментов из [HLS плейлистов (RFC 8216)](https://datatracker.ietf.org/doc/html/rfc8216).
```suggestion
`$hls` правила модифицируют ответ на соответствующий правилу запрос. Они предназначены для удаления сегментов из [HLS плейлистов (RFC 8216)](https://datatracker.ietf.org/doc/html/rfc8216).
```

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$hls=urlpattern` – удалить сегменты чей URL соответствуют паттерну `urlpattern`. Паттерн работает так же, как в базовых URL правилах, однако символы `/`, `$` и `,` в составе `urlpatt
```suggestion
* `||example.org^$hls=urlpattern` – удалить сегменты, URL которых соответствует паттерну `urlpattern`. Паттерн работает так же, как в базовых URL правилах, однако символы `/`, `$` и `,` в составе `urlpattern` необходимо экранировать с помощью `\`.
```

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$hls=/regex/options` – удалить сегменты, чей URL, или, в зависимости от опций, один из тэгов, соответствует регулярному выражению `regex`. Опции `options` модифицируют поведение прав
```suggestion
* `||example.org^$hls=/regex/options` – удалить сегменты, URL которых, или, в зависимости от опций, один из тэгов, соответствует регулярному выражению `regex`. Опции `options` изменяют поведение правила как описано ниже.
```

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` также можно отключить с помощью правил-исключений с модификаторами `$document`, `$content` и `$urlblock`.
А `$badfilter`?

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
без двойного отрицания было бы лучше.

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Если несколько `$hls` правил соответствуют одному и тому же запросу, их эффект суммируется.
Как суммируется - применяются по очереди?

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Краткий пересказ [спецификации](https://datatracker.ietf.org/doc/html/rfc8216):
Краткое содержание лучше, не о повести же речь)

2022-07-11 23:55 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +4. `$hls` правила не могут удалить теги, относящиеся ко всему плей-листу. `$replace` правила могут быть использованы в данным случае.
```suggestion
4. `$hls` правила не могут удалить теги, относящиеся ко всему плей-листу. В данном случае могут быть использованы правила `$replace` .
```

2022-07-13 09:45 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` также можно отключить с помощью правил-исключений с модификаторами `$document`, `$content` и `$urlblock`.
Про `$badfilter` в этих секциях не пишется, `$badfilter` это не исключение :)

2022-07-13 09:47 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Если несколько `$hls` правил соответствуют одному и тому же запросу, их эффект суммируется.
В данном случае не важно, в каком порядке они применяются. Эффект суммируется :)

2022-07-13 09:47 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
А где здесь двойное отрицание?

2022-07-13 12:21 UTC, el-termikael requested changes

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Если несколько `$hls` правил соответствуют одному и тому же запросу, их эффект суммируется.
`$hls`-правил

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$hls=/#UPLYNK-SEGMENT:.*\,ad/t` — удалить все сегменты с соответствующим тэгом.
тегом

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Краткий пересказ [спецификации](https://datatracker.ietf.org/doc/html/rfc8216):
согласна

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +1. HLS плейлист -- это набор текстовых строк.
HLS-плейлист — это набор текстовых строк.

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +2. Строка может быть пустой, быть комментарием (начинается с `#`), тэгом (начинается с `#` и имени тэга) или URL.
тегом (здесь и ниже)

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +4. Тэг может относиться к одному сегменту, т.е. к первой URL-строке, следующей после данного тэга,
Тег может относиться к одному сегменту, т.е. к первой URL-строке, следующей после данного тега, ко всем последующим сегментами (пока не встретится тег с тем же именем) или ко всему плейлисту.

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Замечания, касающиеся `$hls` правил:
`$hls`-правил (здесь и ниже)

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +2. Тэги, относящиеся к нескольким сегментам удаляются, если все эти сегменты были удалены.
Теги, относящиеся к нескольким сегментам, удаляются, если все эти сегменты были удалены.

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +3. `$hls` правила распознают все тэги, описанные в RFC, а также несколько распространненых нестандартны тегов. Все остальные строки, начинающиеся с `#`, считаются комментариями, и остаются нетронутым
3. `$hls`-правила распознают все теги, описанные в RFC, а также несколько распространненых нестандартных тегов. Все остальные строки, начинающиеся с `#`, считаются комментариями и остаются нетронутыми.

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +4. `$hls` правила не могут удалить теги, относящиеся ко всему плей-листу. `$replace` правила могут быть использованы в данным случае.
4. `$hls`-правила не могут удалить теги, относящиеся ко всему плейлисту. В данном случае могут быть использованы правила `$replace` .

2022-07-13 12:21 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Пример работы `$hls` правил:
`$hls`-правил

2022-07-13 12:37 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
Тогда получается, что правила с модификатором `$hls` не могут иметь модификатора `$hls` :)

2022-07-13 12:51 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
Для `$jsonprune` я так же написал, и было норм :)

2022-07-13 12:58 UTC, el-termikael requested changes

2022-07-13 13:01 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +2. теги, относящиеся к нескольким сегментам, удаляются, если все эти сегменты были удалены.
```suggestion
2. Теги, относящиеся к нескольким сегментам, удаляются, если все эти сегменты были удалены.
```

2022-07-13 13:14 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$hls=/regex/options` – удалить сегменты, чей URL, или, в зависимости от опций, один из тэгов, соответствует регулярному выражению `regex`. Опции `options` модифицируют поведение прав
может `где` заменить на `в которых`?

2022-07-13 13:17 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
"не могут"... "кроме". Может слово "других"  лишнее.

2022-07-13 13:19 UTC, ngorskikh commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$hls` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
Ну, `$hls` – это уже модификаторох. Других, кроме перечисленных, быть не может :)

2022-07-18 08:27 UTC, el-termikael approved these changes

2022-07-18 08:27 UTC, merged

2022-08-04 15:25 UTC, contribucious commented
## _(:wave:)_ :bulb: Some small suggestions _(for consistency)_
&nbsp;
1) `regex` → `regexp` &nbsp;—&nbsp; To be consistent, further to [this commit](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1075/commits/db48126bbb0c5e1b7d19e0aabefc034882a83ea1) and [this mini-discussion](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1075#discussion_r896681722).
&nbsp;
:arrow_right_hook: Possibly `regular expression` sometimes instead, when its equivalent is used in the Russian version of the KB.
&nbsp;

2) `options` → `[options]` &nbsp;—&nbsp; Currently, **`$removeparam`** _([EN](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeparam)/[RU](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#removeparam))_ uses `[options]` while **`$hls`** _([EN](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#hls)/[RU](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#hls))_ uses `options`.
&nbsp;

:v: :wink:

2022-08-04 16:25 UTC, ngorskikh commented
@contribucious 
Nice suggestions, you're welcome to open a new pull request :)

2022-08-04 17:16 UTC, contribucious commented
@ngorskikh
I actually wanted to but sometimes the differences are intentional between the English and Russian versions (as I've been told in the past) and … I don't speak Russian at all. That's why for this case I chose the _post_ and not the _pull request_. :wink:

2022-08-04 20:32 UTC, contribucious commented
… but therefore, let's try it anyway! :relaxed:

:arrow_right_hook: _Here you go:_ https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1111