Add $jsonprune modifier descriptions
AdguardTeam/AdguardKnowledgeBase pull request #1086
Opened 2022-06-29 19:16 UTC by ngorskikh

2022-07-03 20:28 UTC, ameshkov requested changes
Please add a disclaimer

2022-07-03 20:28 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +`$jsonprune` rules modify the JSON response of a matching request by removing JSON items that match a modified (see below)
We need a disclaimer that explains that this is only available with CoreLibs 1.10 (i.e. dev builds)

2022-07-06 08:18 UTC, ameshkov submitted a review, later dismissed

2022-07-06 08:25 UTC, slavaleleka approved these changes

2022-07-06 15:48 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$jsonprune=expression` – удалить элементы, соответствующие особому JSONPath выражению `expression` из ответа на запрос к URL, соответствующему `||example.org`.
JSONPath-выражению или выражению JSONPath

2022-07-06 15:49 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +6. Выражения, заканчивающиеся на `..` не поддерживаются.
Выражения, заканчивающиеся на `..`, не поддерживаются.

2022-07-06 15:50 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Существуют различные online инструменты для проверки JSONPath выражений:
online-инструменты для проверки JSONPath-выражений

2022-07-06 15:50 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Пользуясь такого рода инструментами, необходимо иметь в виду, что различные имплементации JSONPath обладают
> Обратите внимание, что различные имплементации JSONPath обладают
уникальными особенностями и могут быть несовместимы друг с другом.

2022-07-06 15:51 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `@@||example.org^$jsonprune` – отключить все `$jsonprune` правила для запросов к URL, соответствующим `||example.org^`.
лучше всё-таки «правила `$jsonprune`», иначе просится дефис (тут и ниже)

2022-07-06 15:52 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `$jsonprune` не могут иметь других модификаторов, кроме `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, и `$xmlhttprequest`.
лишняя запятая после `$match-case`

2022-07-06 15:52 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$jsonprune=\$..[one\, "two three"]` — удалить все вхождения свойств "one" и "two three" в JSON документ.
JSON-документ

2022-07-06 15:52 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `||example.org^$jsonprune=\$.*.*[?(key-eq 'Some key' 'Some value')]` – удалить все элементы на уровне вложенности 3, обладающие свойством "Some key" равным "Some value".
свойством "Some key", равным "Some value".

2022-07-13 08:32 UTC, el-termikael approved these changes

2022-07-13 09:42 UTC, merged