added descriptions of new filters
AdguardTeam/AdguardKnowledgeBase pull request #1095
Opened 2022-07-13 14:00 UTC by el-termikael

2022-07-13 14:08 UTC, zloyden approved these changes

2022-07-13 14:18 UTC, zloyden commented on 01.general/01.adguard-ad-filters/docs.en.md
> +	* Widgets — blocks third-party widgets: online assistants, live support chats, etc.
Кажись не хватает еще `[View rules]` к каждому новому.

2022-07-13 14:24 UTC, zloyden commented on 01.general/01.adguard-ad-filters/docs.en.md
> +	* Widgets — blocks third-party widgets: online assistants, live support chats, etc.
Добавь плез для en
```
[View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt)
[View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_19_Annoyances_Popups/filter.txt)
[View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_20_Annoyances_MobileApp/filter.txt)
[View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_21_Annoyances_Other/filter.txt)
[View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Widgets/filter.txt)
```
для ру
```
[Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt)
[Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_19_Annoyances_Popups/filter.txt)
[Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_20_Annoyances_MobileApp/filter.txt)
[Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_21_Annoyances_Other/filter.txt)
[Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Widgets/filter.txt)
```

2022-07-13 15:44 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +	* Фильтр других раздражителей — блокирует элементы на веб-страницах, не включённые в популярные категории раздражителей.
я бы на последнее место поставил

2022-07-13 15:48 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
> упрощён для лучшей совместимости

не упрощён, а оптимизирован)

2022-07-13 16:18 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
"Фильтр" с большой буквы везде точно нужен?

2022-07-13 16:19 UTC, slavaleleka commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
да тут и "упрощён" нормально подходит, в англ вон "simplified"

2022-07-13 16:21 UTC, slavaleleka commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
предполагаю что как имена собственные да

2022-07-13 16:22 UTC, el-termikael commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
ну а как, это его название

2022-07-13 16:22 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
Так скорее в англ. языке делают.

2022-07-13 16:23 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
ладно

2022-07-13 16:36 UTC, zloyden approved these changes

2022-07-14 15:19 UTC, Alex-302 approved these changes

2022-07-14 15:19 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **Фильтр раздражителей** — блокирует раздражающие элементы на сайтах. Основан на фильтре Fanboy Annoyances List, но не дублирует его. [Посмотреть правила](https://raw.githubusercontent.com/AdguardT
ничего общего наш фильтр с `Fanboy Annoyances List` не имеет, на 100% независимо развивался с самого начала

2022-07-14 15:20 UTC, zloyden commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **Фильтр раздражителей** — блокирует раздражающие элементы на сайтах. Основан на фильтре Fanboy Annoyances List, но не дублирует его. [Посмотреть правила](https://raw.githubusercontent.com/AdguardT
ух, вот эту вторую часть про FA надо снести

2022-07-14 15:26 UTC, Alex-302 requested changes

2022-07-14 15:26 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **Фильтр раздражителей** — блокирует раздражающие элементы на сайтах. Основан на фильтре Fanboy Annoyances List, но не дублирует его. [Посмотреть правила](https://raw.githubusercontent.com/AdguardT
```suggestion
* **Фильтр раздражителей** — блокирует раздражающие элементы на сайтах. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt)
```

2022-07-14 15:26 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.en.md
> +* **Annoyances filter** — blocks irritating elements on web pages. Inspired by Fanboy Annoyances List, but doesn’t duplicate it. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegi
```suggestion
* **Annoyances filter** — blocks irritating elements on web pages. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt)
```

2022-07-14 15:26 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.en.md
>  * **Russian filter** — removes ads from websites in Russian. Initially based on [RU AdList](https://code.google.com/p/ruadlist/) filter but subsequently developed completely independently. Currently,
```suggestion
* **Russian filter** — removes ads from websites in Russian. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt)
```

2022-07-14 15:26 UTC, Alex-302 commented on 01.general/01.adguard-ad-filters/docs.ru.md
>  * **Русский фильтр** — убирает рекламу с сайтов на русском языке. Изначально за основу был взят фильтр [RU AdList](https://code.google.com/p/ruadlist/). В дальнейшем фильтр развивался самостоятельно,
```suggestion
* **Русский фильтр** — убирает рекламу с сайтов на русском языке. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt)
```

2022-07-14 15:33 UTC, Alex-302 submitted a review, later dismissed

2022-07-14 15:34 UTC, zloyden approved these changes

2022-07-14 15:48 UTC, ss-orlova submitted a review, later dismissed

2022-07-15 10:38 UTC, vbagirov requested changes

2022-07-15 10:38 UTC, vbagirov commented on 01.general/01.adguard-ad-filters/docs.en.md
> +Includes the following AdGuard filters:
добавить в скобках 
(all of them can be enabled separately from the Annoyances filter)

2022-07-15 10:38 UTC, vbagirov commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +Включает следующие фильтры AdGuard:
добавить аналогично англ:

(все они могут быть включены независимо от фильтра раздражителей)

2022-07-15 11:29 UTC, vbagirov approved these changes

2022-07-15 11:30 UTC, vbagirov approved these changes

2022-07-15 11:45 UTC, zloyden submitted a review, later dismissed

2022-07-15 13:34 UTC, ss-orlova commented on 01.general/01.adguard-ad-filters/docs.ru.md
> +* **DNS-фильтр** — составлен из нескольких фильтров (Базовый фильтр AdGuard, Фильтр социальных сетей, Фильтр счётчиков и систем аналитики, Фильтр мобильной рекламы, EasyList и EasyPrivacy), и специал
запятая лишняя после скобки

2022-07-18 09:18 UTC, ameshkov submitted a review, later dismissed
Check my suggestions before merging it

2022-07-18 09:18 UTC, ameshkov commented on 01.general/01.adguard-ad-filters/docs.en.md
> +	* Cookie Notices — blocks cookie notices on web pages. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt)
```suggestion
	* **Cookie Notices** — blocks cookie notices on web pages. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt)
```

2022-07-18 09:18 UTC, ameshkov commented on 01.general/01.adguard-ad-filters/docs.en.md
> +	* Mobile App Banners — blocks banners that promote mobile apps of websites. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_20_Annoyances_MobileApp/f
```suggestion
	* **Mobile App Banners** — blocks banners that promote mobile apps of websites. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_20_Annoyances_MobileApp/filter.txt)
```

2022-07-18 09:18 UTC, ameshkov commented on 01.general/01.adguard-ad-filters/docs.en.md
> +	* Widgets — blocks third-party widgets: online assistants, live support chats, etc. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Wid
```suggestion
	* **Widgets** — blocks third-party widgets: online assistants, live support chats, etc. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Widgets/filter.txt)
```

2022-07-18 09:18 UTC, ameshkov commented on 01.general/01.adguard-ad-filters/docs.en.md
> +	* Other Annoyances — blocks elements that do not fall under the popular categories of annoyances. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_21_
```suggestion
	* **Other Annoyances** — blocks elements that do not fall under the popular categories of annoyances. [View rules](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_21_Annoyances_Other/filter.txt)
```

2022-07-18 09:29 UTC, ameshkov approved these changes

2022-07-18 09:30 UTC, merged