Fixes to the VPN section of KB
AdguardTeam/AdguardKnowledgeBase pull request #1096
Opened 2022-07-14 12:05 UTC by anastasiia-fedotova

Fixed to files FAQ and Features

2022-07-14 12:56 UTC, vbagirov requested changes

2022-07-14 12:56 UTC, vbagirov commented on 11.vpn/03.features/docs.en.md
> +AdGuard VPN is a VPN service created by our company. An in-house developed VPN protocol makes it unique among competitors. AdGuard VPN is available as a browser extension for Chrome,Firefox, and Edge
>Chrome,Firefox

пробел потерялся

2022-07-14 12:56 UTC, vbagirov commented on 11.vpn/03.features/docs.en.md
> +* 2 devices with enabled AdGuard VPN (there can be more devices overall, but only five can be used simultaneously)
в скобках тоже five на two поменять

2022-07-14 12:56 UTC, vbagirov commented on 11.vpn/04.FAQ/docs.en.md
> +Most likely you are reading this because you’ve seen the “Maximum number of connections reached” warning. One AdGuard VPN subscription covers **5 simultaneous connections** (to any devices you want).
>(to any devices you want)

неуклюже, на мой взгляд. Скорее коннекшны не к девайсам, а девайсом к впн-серверу. Мб так?

One AdGuard VPN subscription covers up to **5 simultaneously connected devices** (of any types, in any combination).

2022-07-14 12:56 UTC, vbagirov commented on 11.vpn/04.FAQ/docs.en.md
> +We grant our customers a possibility to return 100% of funds they spent on AdGuard 1 year subscriptions purchased from https://adguard-vpn.com/ (for subscriptions purchased elsewhere, look for the re
у нас выше было 1-year, 2-year и т.д., а тут через пробел, как мы решили писать?

2022-07-14 12:56 UTC, vbagirov commented on 11.vpn/04.FAQ/docs.ru.md
> +Скорее всего, вы читаете это, потому что видели предупреждение “Максимальное количество подключений достигнуто”. Одна подписка AdGuard VPN распространяется на **5 одновременных подключений** (к любым
аналогично англу поменять бы

2022-07-14 14:41 UTC, vbagirov approved these changes

2022-07-14 14:43 UTC, merged

2022-07-21 08:51 UTC, el-termikael commented on 11.vpn/04.FAQ/docs.en.md
> +We grant our customers a possibility to return 100% of funds they spent on AdGuard 1 year subscriptions purchased from https://adguard-vpn.com/ (for subscriptions purchased elsewhere, look for the re
через дефис надо