Update description of the `$domain` modifier
AdguardTeam/AdguardKnowledgeBase pull request #1109
Opened 2022-07-27 13:02 UTC by sxgunchenko

Link for reference: https://github.com/AdguardTeam/CoreLibs/issues/1550

2022-07-27 13:48 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +    * [Wildcard support for TLD](#wildcard-for-tld)
базовых правил это по прежнему касается?

2022-07-28 07:40 UTC, sxgunchenko commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +    * [Wildcard support for TLD](#wildcard-for-tld)
Да, но у них есть своё описание в разделе для `$domain`. А в этом разделе описано как раз для небазовых.

2022-07-29 16:43 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +> **Compatibility with different versions of AdGuard.** Rules with regular expressions in the `$domain` modifier are supported by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.1
может такое ещё стоит добавить?
```
Rules with `$domain` modifier as `regular_domain` or `any_tld_domain` supported by all AdGuard products.
```

2022-07-29 20:27 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +> **Compatibility with different versions of AdGuard.** Rules with regular expressions in the `$domain` modifier are supported by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.1
Да, явно указать это не помешало бы.

2022-07-30 14:18 UTC, ameshkov requested changes
Please add information about other AG products

2022-07-30 14:18 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +> **Compatibility with different versions of AdGuard.** Rules with regular expressions in the `$domain` modifier are supported by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.1
```suggestion
> **Compatibility with different versions of AdGuard.** Rules with regular expressions in the `$domain` modifier are supported by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.11 or later**.
> Rules with `$domain` modifier as `regular_domain` or `any_tld_domain` supported by all AdGuard products.
```

2022-08-01 12:27 UTC, slavaleleka approved these changes

2022-08-01 14:54 UTC, NataKiss submitted a review, later dismissed

2022-08-14 18:17 UTC, contribucious commented
Hi. Before the merge, same remark as for [`$hls`](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1111/files) I suppose …
Namely, `regex` → `regexp`. :v: :wink:

2022-09-12 11:10 UTC, ameshkov approved these changes

2022-09-12 11:12 UTC, merged