Add Chinese translation
AdguardTeam/AdguardKnowledgeBase pull request #1113
Opened 2022-08-21 00:41 UTC by hacamer

2022-08-21 03:54 UTC, hacamer reviewed
fix Chinese translation mistake

2022-08-25 08:27 UTC, DashaBu requested changes

2022-08-25 08:27 UTC, DashaBu commented on 01.general/21.local-adguard/docs.zh.md
> +1. Adguard是一个网络级内容阻止程序，因此它不能简单地将自定义JavaScript和CSS添加到网页中，例如浏览器扩展程序的操作。但是，这样做对于高质量的内容拦截至关重要。
AdGuard 是一个网络级内容阻止程序，因此它不能简单地将自定义 JavaScript 和 CSS 添加到网页中，例如浏览器扩展程序的操作。

2022-08-25 08:27 UTC, DashaBu commented on 01.general/21.local-adguard/docs.zh.md
> +3. `local.adguard.org`AdGuard 在网络级别拦截到域IP 地址的连接并在本地进行处理。这就是为什么该域具有多年不变的“静态”IP 地址。
`local.adguard.org` AdGuard 在网络级别拦截到 IP 地址的连接并在本地进行处理。这就是为什么该域具有多年不变的“静态” IP 地址。

2022-08-25 08:27 UTC, DashaBu commented on 01.general/21.local-adguard/docs.zh.md
> +* 可以使用私有子网中的一些IP地址，但是该解决方案具有两个弊端
可以使用私有子网中的一些 IP 地址，但是该解决方案具有两个弊端。

2022-08-25 08:27 UTC, DashaBu commented on 01.general/21.local-adguard/docs.zh.md
> +    * 首先，很有可能与现有的Intranet服务相交并破坏对其的访问
首先，很有可能与现有的 Intranet 服务冲突并破坏对其的访问。

2022-08-25 08:27 UTC, DashaBu commented on 01.general/21.local-adguard/docs.zh.md
> +    * 其次，一些DNS服务器可能会认为这是DNS重新攻击的攻击，并拒绝回应 ` local.adguard.org`
其次，一些 DNS 服务器可能会认为这是 DNS 重新绑定的攻击，并拒绝回应 ` local.adguard.org`。

2022-08-25 08:35 UTC, el-termikael commented
@hacamer Hi, thank you for adding Chinese translation! Please check the comments @DashaBu left to your pull request

2022-08-25 10:42 UTC, hacamer commented
> @hacamer Hi, thank you for adding Chinese translation! Please check the comments @DashaBu left to your pull request

@el-termikael Hi ,I checked the comments and the modifications are correct but I don't know how to merge it🤣

2022-08-25 12:18 UTC, el-termikael approved these changes

2022-08-29 07:10 UTC, el-termikael commented
@hacamer if you agree with the changes @DashaBu requested, you need to make them in your current branch and create one more commit
You can find more details in GitHub documentation: https://docs.github.com/en/pull-requests

2022-08-31 03:34 UTC, closed without merging

2022-08-31 03:37 UTC, hacamer commented
> @hacamer if you agree with the changes @DashaBu requested, you need to make them in your current branch and create one more commit You can find more details in GitHub documentation: https://docs.github.com/en/pull-requests

@el-termikael Hi I still don't know how to merge I have opened a new pull request this pull request will be closed
New pull request: #1118