AGM-1313-Possible DNS Leaks
AdguardTeam/AdguardKnowledgeBase pull request #1122
Opened 2022-09-12 13:45 UTC by anastasiia-fedotova

2022-09-12 13:54 UTC, ameshkov approved these changes

2022-09-13 12:23 UTC, vbagirov requested changes

2022-09-13 15:13 UTC, vbagirov requested changes

2022-09-13 15:13 UTC, vbagirov commented on 02.windows/04.solving-problems/12.possible-dns-leaks/docs.ru.md
> +* затем найдите раздел *Список пользовательских резервных (fallback) серверов* и укажите сервера по одному в строке
я настаиваю на "серверы" вместо "сервера"

2022-09-13 15:27 UTC, EugeneOne1 commented on 02.windows/04.solving-problems/12.possible-dns-leaks/docs.ru.md
> +В AdGuard для Windows можно указать DNS-сервер, чтобы он обрабатывал запросы вместо системных DNS-адресов, которые предоставляются провайдером (если это не отменено в настройках системы). Замена DNS-
Мне кажется, не совсем корректно говорить, что системные DNS адреса обрабатывают запросы.

Я бы сказал "В AdGuard для Windows можно указать адрес DNS-сервера, который будет обрабатывать запросы вместо системного DNS-сервера (предоставляется провайдером, если явно не перенастроен в настройках системы)".

2022-09-13 16:02 UTC, vbagirov approved these changes

2022-09-13 16:28 UTC, EugeneOne1 approved these changes

2022-09-14 06:10 UTC, merged