Update Certificate Transparency status
AdguardTeam/AdguardKnowledgeBase pull request #1124
Opened 2022-09-20 11:19 UTC by ngorskikh

2022-09-20 11:20 UTC, ngorskikh commented on 01.general/11.https-filtering/01.https-filtering-known-issues/docs.ko.md
> +TODO: synchronize with the English and Russian version.
Вопрос: для Корейского мы используем гугл, или есть специальный человек? :)

2022-09-20 11:52 UTC, el-termikael commented on 01.general/11.https-filtering/01.https-filtering-known-issues/docs.ko.md
> +TODO: synchronize with the English and Russian version.
@ngorskikh на корейский у нас переводит @NataKiss

2022-09-21 13:18 UTC, NataKiss commented on 01.general/11.https-filtering/01.https-filtering-known-issues/docs.ko.md
> +TODO: synchronize with the English and Russian version.
внесла изменения

2022-09-21 13:32 UTC, el-termikael requested changes

2022-09-21 13:32 UTC, el-termikael commented on 01.general/11.https-filtering/01.https-filtering-known-issues/docs.ru.md
> +Однако, этих механизмов недостаточно для обнаружения вредоносных сайтов, которые используют сертификаты, выданные по
```suggestion
Однако этих механизмов недостаточно для обнаружения вредоносных сайтов, которые используют сертификаты, выданные по ошибке или выданные скомпрометированным центром сертификации. Certificate Transparency призван устранить такие угрозы, сделав процедуру выдачи SSL-сертификатов открытой и прозрачной для всех.
```

2022-09-21 13:54 UTC, el-termikael approved these changes

2022-09-21 13:54 UTC, merged