impore path modifier description for non-basic rules
AdguardTeam/AdguardKnowledgeBase pull request #1132
Opened 2022-10-26 16:11 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/1071

2022-10-26 19:57 UTC, el-termikael requested changes

2022-10-26 19:57 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
>  > Обратите внимание, что модификатор пути также соответствует параметрам запроса.
ой-ой, модификатор пути какой-то)
```suggestion
> Обратите внимание, что модификатор `$path` также соответствует параметрам запроса.
```

2022-10-26 19:57 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +* `[$path]example.com##.textad` — hides a `div` with a class `textad` at the main page of `example.com`
тут и в других пунктах списка тире бы убрать

2022-10-26 19:57 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `[$path]example.com##.textad` — скрывает `div` с классом `textad` на главной странице сайта `example.com`
и тут тире лишние

2022-10-28 09:23 UTC, sxgunchenko approved these changes

2022-10-28 13:28 UTC, el-termikael approved these changes

2022-10-28 14:04 UTC, merged