Restricted account articles (VPN)
AdguardTeam/AdguardKnowledgeBase pull request #577
Opened 2020-08-18 17:56 UTC by vbagirov

+EN
+RU

2020-08-18 18:51 UTC, artemiv4nov requested changes

2020-08-18 18:51 UTC, artemiv4nov commented on 04.android/06.solving-problems/12.restricted-profile/docs.en.md
> +> On the windows platform, **Samsung** owners may need to install [this utility](https://developer.samsung.com/mobile/android-usb-driver.html).
windows? О чем речь?

2020-08-18 18:51 UTC, artemiv4nov commented on 04.android/06.solving-problems/12.restricted-profile/docs.en.md
> +> On the windows platform, **Samsung** owners may need to install [this utility](https://developer.samsung.com/mobile/android-usb-driver.html).
а, кажется, понял. 
Может быть тогда с большой буквы?

2020-08-18 18:51 UTC, artemiv4nov commented on 11.vpn/05.solving-problems/docs.en.md
> +> On the windows platform, **Samsung** owners may need to install [this utility](https://developer.samsung.com/mobile/android-usb-driver.html).
И здесь тоже с большой

2020-08-18 18:51 UTC, artemiv4nov commented on 11.vpn/05.solving-problems/docs.en.md
> +- **Terminal** if you are using **macOS**;
Вроде `Mac OS`

2020-08-18 18:51 UTC, artemiv4nov commented on 11.vpn/05.solving-problems/docs.ru.md
> +> Пожалуйста, обратите внимание, что данный вариант доступен, начиная с версии **AdGuard v3.5 nightly 6**. Для получения актуальной версии, перейдите по [указанной ссылке](https://adguard.com/ru/beta
Этот блок вообще можно удалить, потому что приложение ещё в стадии бета тестирования, и это пока редко кому понадобится. Просто по-тихому внедрим, и все

2020-08-19 08:22 UTC, vbagirov commented on 11.vpn/05.solving-problems/docs.en.md
> +- **Terminal** if you are using **macOS**;
По-моему "mac OS" вообще :) поправлю

2020-08-19 08:24 UTC, vbagirov commented on 11.vpn/05.solving-problems/docs.en.md
> +- **Terminal** if you are using **macOS**;
А нет, ты был прав

2020-08-19 08:26 UTC, vbagirov commented on 11.vpn/05.solving-problems/docs.en.md
> +- **Terminal** if you are using **macOS**;
Хотя не, правильно было изначально. Точно совершенно "macOS"

2020-08-19 11:32 UTC, artemiv4nov approved these changes

2020-08-19 11:32 UTC, merged