updated two stamps for AdGuard DNS servers
AdguardTeam/AdguardKnowledgeBase pull request #619
Opened 2020-09-04 09:12 UTC by el-termikael

2020-09-04 10:08 UTC, vozersky approved these changes

2020-09-04 11:06 UTC, vozersky approved these changes

2020-09-05 15:49 UTC, KizunaH commented
@el-termikael @vozersky this PR conflict with https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/582
It has many changes including new providers, mode extensions and table adjustments.

@el-termikael Can you create new PR once it merged? unfortunately i dont have a time these days otherwise i'll do and now it has more providers :/

2020-09-16 06:45 UTC, jackiebrewster307 requested changes
Permission access

2021-01-20 13:32 UTC, vbagirov approved these changes

2021-01-20 13:32 UTC, merged