credits (ru)
AdguardTeam/AdguardKnowledgeBase pull request #624
Opened 2020-09-07 15:43 UTC by Dariamag

2020-09-07 15:43 UTC, Dariamag commented
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/583

2020-09-07 15:59 UTC, m67055 commented
Hick you aut from my email asshols

On 9/7/20, Daria Magdik <notifications@github.com> wrote:
> https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/583
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/624#issuecomment-688401537

2020-09-08 09:04 UTC, ameshkov requested changes
Посмотри как я поменял и сделай тут также: https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/583/commits/ebb27a30616647c1f938a628efbdb9f1e40f47a2

2020-09-08 11:09 UTC, ameshkov submitted a review, later dismissed

2020-09-08 11:15 UTC, ameshkov approved these changes

2020-09-08 11:16 UTC, merged