Create docs.ru.md
AdguardTeam/AdguardKnowledgeBase pull request #645
Opened 2020-09-10 15:15 UTC by Dariamag

Russian version for https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/643

2020-09-10 15:24 UTC, slavaleleka requested changes

2020-09-10 15:24 UTC, slavaleleka commented on 01.general/21.filters-optimization/docs.ru.md
> +Для каждого фильтра AdGuard составляет две версии: полную и оптимизированную. Оптимизированная версия более лёгкая и не содержит правил, которые вообще не используются или используются редко. Поэтому
сам AdGuard не делает этого, это типа под капотом. лучше проще:
"Для каждого фильтра существует две его версии"

2020-09-10 15:24 UTC, slavaleleka commented on 01.general/21.filters-optimization/docs.ru.md
> +Обычно, если какое-то правило используется редко, оно просто убирается из фильтра. Поэтому, если вы добавляете правило, которое нежелательно удалять, используйте тэг [*NOT_OPTIMIZED*](https://kb.adgu
я бы прям написал [хинт *NOT_OPTIMIZED*]

2020-09-10 15:24 UTC, slavaleleka commented on 01.general/21.filters-optimization/docs.ru.md
> +Обычно, если какое-то правило используется редко, оно просто убирается из фильтра. Поэтому, если вы добавляете правило, которое нежелательно удалять, используйте тэг [*NOT_OPTIMIZED*](https://kb.adgu
"убирается" как-будто оставляет некую недосказанность (типа куда убираются? до лучших времен?) поэтому я бы написал так:
"оно удаляется из фильтра"

2020-09-10 15:24 UTC, slavaleleka commented on 01.general/21.filters-optimization/docs.ru.md
> +>Иными словами, `percent` это "уровень сжатия". Например, "уровень сжатия" для Базового фильтра настроен на 40%. Это значит, что алгоритм оптимизации вырежет 60% правил.
вырежет → удалит

2020-09-10 15:24 UTC, slavaleleka commented on 01.general/21.filters-optimization/docs.ru.md
> +Вот так, например, выглядят версии Базового фильтра:
... версии Базового фильтра для браузерного расширения AdGuard:

2020-09-10 15:24 UTC, slavaleleka commented on 01.general/21.filters-optimization/docs.ru.md
> +- Расширение браузера AdGuard может использовать обе версии, пользователи могут выбрать нужную в разделе «Настройки»/«Разное» (по умолчанию используются полные версии).
Расширение браузера AdGuard → Браузерное расширение AdGuard

2020-09-10 15:54 UTC, slavaleleka approved these changes

2020-09-11 10:50 UTC, ameshkov requested changes

2020-09-11 10:50 UTC, ameshkov commented on 01.general/21.filters-optimization/docs.ru.md
> +**"Предустановленные" параметры оптимизации фильтров:**
Не надо, это меняется. Просто как пример один фильтр покажите, скажите вот так оно настраивается.

2020-09-14 17:46 UTC, Dariamag commented
Закрываю эту задачу, переношу эту инфу в другую статью, как просил Андрей: https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/650

2020-09-14 17:46 UTC, closed without merging