EN text
AdguardTeam/AdguardKnowledgeBase pull request #646
Opened 2020-09-11 16:10 UTC by vbagirov

- no screenshots yet
- no specific proxies manuals

2020-09-11 16:55 UTC, vozersky commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.en.md
> +## Enabling kernel extension in Big Sur
вот это в самый низ надо, не особо рекомендуется

2020-09-11 16:58 UTC, ameshkov requested changes
Еще надо добавить пункт про SSH: https://github.com/AdguardTeam/AdguardForMac/issues/735
Иногда возникают с ним проблемы. Решение - использовать ssh установленный из brew.

А еще надо уточнить в каждом из пунктов из-за какого бага macOS это возникает (ссылку на девелоперский форум взять у Сереги например -- там она одна и та же для некоторых багов).

2020-09-11 16:58 UTC, ameshkov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.en.md
> +## Enabling kernel extension in Big Sur
Вот это последним пунктом - мы это не рекомендуем вообще

2020-09-11 16:58 UTC, ameshkov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.en.md
> +In Big Sur, any server from a network that's filtered by AdGuard won't be able to reach your Mac if you use it as a server (and by default AdGuard filters all traffic except for localhost). To avoid
Какие those? Нужно уточнить что те, с которых коннекшн идет.

2020-09-14 12:59 UTC, vbagirov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.en.md
> +## Enabling kernel extension in Big Sur
@ameshkov а как быть с твоей фразой из таска?
"Using "Automatic proxy" filtering mode when nothing else helps."

2020-09-14 18:37 UTC, vbagirov commented
Пока не хватает ру скринов, доделаем завтра

2020-09-15 11:24 UTC, Maxim-Butov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.ru.md
> +5) Выберите *Автоматический прокси*.
У нас нет перевода этого окна в русскоязычной версии, т.е. там написано Automatic proxy итд.

2020-09-15 11:24 UTC, Maxim-Butov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.ru.md
> +2) Кликните *Перезапуск…*
"Перезагрузить..."

2020-09-15 11:24 UTC, Maxim-Butov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.ru.md
> +4) Кликните по кнопке *Утилиты*.
в Recovery mode все по английски, даже если русский на самом маке. Ну по крайней мере у меня так сейчас.

2020-09-15 11:31 UTC, Maxim-Butov submitted a review, later dismissed

2020-09-15 11:56 UTC, vozersky approved these changes

2020-09-15 12:06 UTC, ameshkov approved these changes

2020-09-15 12:45 UTC, merged