Improve pre-processor directives part
AdguardTeam/AdguardKnowledgeBase pull request #655
Opened 2020-09-15 16:31 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/461

https://github.com/AdguardTeam/AdguardForiOS/issues/1104
https://github.com/AdguardTeam/AdguardForiOS/issues/819

2020-09-16 11:14 UTC, vbagirov requested changes

2020-09-16 11:14 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +! for all AdGuard propucts except of AdGuard for Safari
except of не говорят, либо просто except, либо except for

2020-09-16 11:14 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +Safari is notoriously known for its harsh 50k max limit for filtering rules in content blockers. But AdGuard for Safari and AdGuard for iOS max rule count raised to 300k by splitting them into severa
max rule count raised -> raised max rule count

2020-09-16 11:14 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +Safari is notoriously known for its harsh 50k max limit for filtering rules in content blockers. But AdGuard for Safari and AdGuard for iOS max rule count raised to 300k by splitting them into severa
Или 
But in AdGuard for Safari and AdGuard for iOS max rule count is raised to 300k by splitting them into several content blockers.

2020-09-16 14:00 UTC, vbagirov requested changes

2020-09-16 14:00 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +#### Влияние на блокировщика контента Safari
"Влияние на блокировщик контента Safari"

2020-09-16 14:00 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +В Safari существует строгое ограничение в 50 тысяч правил на один блокировщик контента. Но в AdGuard для Safari и в AdGuard для iOS максимальное число поддерживаемых правил увеличено до 300 тысяч. Эт
"независимы"

2020-09-16 16:35 UTC, vbagirov approved these changes

2020-09-17 10:53 UTC, ameshkov approved these changes

2020-09-17 10:53 UTC, merged