Update
AdguardTeam/AdguardKnowledgeBase pull request #673
Opened 2020-10-01 16:14 UTC by lolka4toli

New info about Firefox browser

2020-10-01 16:22 UTC, vbagirov requested changes

2020-10-01 16:22 UTC, vbagirov commented on 04.android/06.solving-problems/13.firefox-certificates/docs.en.md
> +If you can't install the certificate directly into the browser itself (most of the time this happens under v81.1.1), try method 1 described below. If that doesn't work too, try method 2 — it takes up
most of the time this happens in versions older than v81.1.1

2020-10-02 14:36 UTC, lolka4toli commented on 04.android/06.solving-problems/13.firefox-certificates/docs.ru.md
> +Чтобы начать использовать пользовательские сертификаты в **последней стабильной** версии, убедитесь, что вы обновлены до 81.1.1 и новее. Для неё, beta и nightly версии (и браузерах на основе Firefox)
Прости, я опять всё переписал 😄 
Абзац со «Чтобы начать...» я предлагаю вообще убрать. Структура такая:

[Название] Ручная установка сертификата безопасности в браузер Firefox

[Вступительный абзац]Различные версии Firefox требуют разных подходов для осуществления HTTPS-фильтрации. Как правило, проблема установки пользовательского сертификата возникает до релизной версии 81.1.1. Для решения воспользуйтесь Методом 1, описанным ниже. Он также подходит для nightly и beta версии Firefox.

[Инструкция] Предоставление доступа к сертификатам

Метод 1: Сертификат находится в пользовательском хранилище

2020-10-02 14:41 UTC, lolka4toli commented on 04.android/06.solving-problems/13.firefox-certificates/docs.ru.md
> +Чтобы начать использовать пользовательские сертификаты в **последней стабильной** версии, убедитесь, что вы обновлены до 81.1.1 и новее. Для неё, beta и nightly версии (и браузерах на основе Firefox)
И английский.

[Название] Manual installation of the security certificate into the Firefox browser

[Вступительный абзац] Different versions of Firefox browser require different approaches for AdGuard to perform HTTPS-filtering. Generally, an installation of user's certificate problem appears before v81.1.1. To solve this issue, try Method 1 described below. It also works with nightly– and beta– version of Firefox browser.

2020-10-02 15:20 UTC, vbagirov commented on 04.android/06.solving-problems/13.firefox-certificates/docs.ru.md
> +Различные версии Firefox требуют разных подходов для осуществления [HTTPS-фильтрации](https://kb.adguard.com/ru/general/https-filtering). Как правило, проблема установки пользовательского сертификата
Мне не нравится формулировка "до такой-то версии Firefox". Лучше писать "в версиях Firefox до такой-то" или "старее такой-то".

2020-10-02 15:26 UTC, vbagirov commented on 04.android/06.solving-problems/13.firefox-certificates/docs.ru.md
> +Чтобы начать использовать пользовательские сертификаты в **последней стабильной** версии, убедитесь, что вы обновлены до 81.1.1 и новее. Для неё, beta и nightly версии (и браузерах на основе Firefox)
Честно говоря, тут логика утеряна немного. Если последняя стабильная, то очевидно она уже старше 81.1.1. Давай так:

Чтобы начать использовать пользовательские сертификаты в стабильной, бета- или nightly-версии Firefox (или другого браузера на основе Firefox), убедитесь, что ваш браузер обновлён до версии 81.1.1 или выше. В этом соучае вам необходимо активировать скрытую опцию в настройках браузера:

2020-10-02 15:27 UTC, vbagirov requested changes
см. комменты выше

2020-10-02 16:34 UTC, vbagirov approved these changes

2020-10-02 16:38 UTC, merged