Disabling redirect rules
AdguardTeam/AdguardKnowledgeBase pull request #720
Opened 2020-12-03 13:02 UTC by sxgunchenko

Related CoreLibs issue:
https://github.com/AdguardTeam/CoreLibs/issues/1388

2020-12-03 13:09 UTC, vbagirov requested changes

2020-12-03 13:09 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +* `@@||example.org^$redirect=redirectName` will disable the rule with `$redirect=redirectName` for any request matching `||example.org^`.
`@@||example.org^$redirect=redirectName` will disable all rules with `$redirect=redirectName` for any request that matches `||example.org^`.

2020-12-03 13:09 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `@@||example.org^$redirect=redirectName` отключит правила с `$redirect=redirectName`, соответствующие `||example.org^`.
`@@||example.org^$redirect=redirectName` отключит правила с `$redirect=redirectName` для всех запросов, соответствующих `||example.org^`.

2020-12-03 13:09 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +* `@@||example.org^$redirect` отключит все правила `$redirect`, соответствующие `||example.org^`.
`@@||example.org^$redirect` отключит все правила `$redirect` для всех запросов, соответствующих `||example.org^`.

2020-12-03 15:05 UTC, vbagirov approved these changes

2020-12-14 19:53 UTC, ameshkov approved these changes

2020-12-14 21:42 UTC, merged