$denyallow modifier \gh-763
AdguardTeam/AdguardKnowledgeBase pull request #767
Opened 2021-03-12 15:57 UTC by vbagirov

2021-03-12 16:13 UTC, sxgunchenko commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>Note that `domain=` option is required!
в остальных местах на модификатор ссылаются немного в другом стиле: `$domain` и используется не option, а modifier

2021-03-15 13:26 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>Note that `domain=` option is required!
я не спец конечно, но тут в примере точно видно, что `domain=`:

```*$third-party,script,denyallow=x.com|y.com,domain=a.com|b.com```

Ну и собственно тут модификатор сам как будто бы denyallow, а domain это некий параметр?

2021-03-15 13:29 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>Note that `domain=` option is required!
модификаторы указываются после `$` через запятую, то есть тут их 4 штуки

2021-03-15 13:30 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>Note that `domain=` option is required!
а по отдельности их названия пишутся именно с `$`
https://uploads.adguard.com/slbdzdr7y3nf.png

2021-03-15 13:52 UTC, sxgunchenko commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +>Обратите внимание, что [модификатор `$domain`](#domain-modifier) является обязательной!
обязательным

2021-03-15 13:57 UTC, sxgunchenko submitted a review, later dismissed

2021-03-15 13:59 UTC, slavaleleka approved these changes

2021-03-15 19:10 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +Данный модификатор упрощает создание правил, запрещющих определённое поведение по умолчанию при наличии исключений в статических фильтрах.
> определённое поведение

какое поведение?
Его назначение блокировать все ресурсы, кроме перечисленных в `denyallow`. Т.е. белый список.

2021-03-24 20:08 UTC, ameshkov requested changes

2021-03-24 20:08 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +This modifier makes it easier to implement default-deny/allow-exceptionally in static filter lists.
Tbh, I don't like how it's worded.

@sxgunchenko can we somehow rephrase this and use AdGuard terminology.

2021-03-24 20:21 UTC, ameshkov requested changes
The spec needs to be changed after we come up with a proper one in the CL task:
https://github.com/AdguardTeam/CoreLibs/issues/1304#issuecomment-806161108

2021-04-19 13:06 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +**AdGuard for Safari and AdGuard for iOS** convert $denyallow rule into blocking rule and additional exception rules:
Вот это лучше убрать в "цитату" типа такого:

> **AdGuard for Safari and AdGuard for iOS** convert $denyallow rule into a blocking rule and additional exception rules.
> For example, the rule `*$script,domain=a.com|~b.com,denyallow=x.com|y.com`
> will be converted to:
> ```
> *$script,domain=a.com|~b.com
> @@||x.com$script,domain=a.com|~b.com
> @@||y.com$script,domain=a.com|~b.com
> ```

2021-05-06 15:39 UTC, ameshkov requested changes
1. Resolve conflicts
2. Add $denyallow modifier to DNS filtering syntax description: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#denyallow

2021-07-06 07:22 UTC, sxgunchenko submitted a review, later dismissed

2021-07-06 09:40 UTC, ameshkov submitted a review, later dismissed

2021-07-06 10:41 UTC, merged