$specifichide modifier description /gh-760
AdguardTeam/AdguardKnowledgeBase pull request #771
Opened 2021-03-15 11:44 UTC by vbagirov

2021-03-15 11:50 UTC, sxgunchenko requested changes

2021-03-15 11:50 UTC, sxgunchenko commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +                * [$specifichide](#specifichide-modifier)
specific-правило в разделе для generic получается :(
мне кажется, надо либо убрать раздел generic, либо вынести specifichide на уровень выше

2021-03-15 11:53 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +                * [$specifichide](#specifichide-modifier)
можно после $elemhide'а или вместе с ним в отдельный подпункт `Cosmetic rules` вынесты

2021-03-15 11:56 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +                * [$specifichide](#specifichide-modifier)
@Alex-302 говорит что это в дженерик входит

2021-03-15 12:16 UTC, sxgunchenko commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +                * [$specifichide](#specifichide-modifier)
ну просто в начале раздела написано:
```Before we can proceed to the next modifiers, we have to make a definition of _generic rules_. The rule is generic if it is not limited to specific domains.```
что не подходит для specifichide

2021-03-15 13:17 UTC, slavaleleka approved these changes

2021-03-15 13:20 UTC, sxgunchenko approved these changes

2021-03-15 13:23 UTC, merged

2021-03-26 12:07 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +            * [$specifichide](#specifichide-modifier)
@vbagirov лучше в секцию "Generic rules" его - подвинь чуть

2021-03-26 12:07 UTC, ameshkov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +##### **`specifichide`**
И тут +1 уровень