[AGM-863] How to debug filters
AdguardTeam/AdguardKnowledgeBase pull request #801
Opened 2021-04-20 15:59 UTC by vbagirov

Closes #328

2021-04-20 16:48 UTC, Alex-302 requested changes
Also add examples of debugging Extended CSS

2021-04-20 16:48 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +* In **AdGuard for Android** it's a separate item in the side menu;
and in Assistant, the log for specific app or site.

2021-04-20 16:48 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +* In **AdGuard browser extensions** it's accessible from the *Miscellaneous* settings tab or by right-clicking the extension icon.
Only Chromium and Firefox based browsers filtering log show applied 
- element hiding rules(including CSS, ExtCSS)
- JS and scriptlets.

2021-04-20 16:48 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +**Debugging a single selector**
describe debugging

2021-04-20 16:48 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +#$#.banner { display: none; debug: true; }
`#$?#`

2021-04-20 16:48 UTC, Alex-302 commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +#$#.banner { display: none; debug: global; }
`#$?#`

2021-04-21 09:15 UTC, Sergey-Lyapin commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +If you're using AdGuard browser extension and want to debug a [scriptlet rule](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#scriptlets), you can get additional information by s
Maybe we should add a more detailed description of debugging with scriptlets and add examples?

For example, these scriptlets can be useful for debugging:

```
debug-current-inline-script
debug-on-property-read
debug-on-property-write
log-addEventListener
log-eval
log
```

2021-04-21 14:52 UTC, slavaleleka requested changes
[requestAnimationFrame](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#prevent-requestanimationframe), [prevent-setInterval](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#prevent-setinterval) and [prevent-setTimeout](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#prevent-settimeout) can be used without parameters for debug purposes

2021-04-22 14:59 UTC, slavaleleka submitted a review, later dismissed

2021-04-22 23:47 UTC, slavaleleka approved these changes

2021-04-23 15:50 UTC, merged