Redirect-rule modifier description
AdguardTeam/AdguardKnowledgeBase pull request #817
Opened 2021-05-11 14:33 UTC by el-termikael

Closes #815

2021-05-11 14:37 UTC, vbagirov requested changes

2021-05-11 14:37 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +#### `redirect-rule`
В жирненький надо завернуть, чтобы было как везде

2021-05-11 14:37 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +This is basically an alias to $redirect since it has the same "redirection" values and the logic is almost similar. The difference is that $redirect-rule is applied only in the case when the target r
$redirect и $redirect-rule завернуть в такие кавычки: `

2021-05-11 14:37 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +`||example.org/script.js`
Строчки с примерами завернуть сверху и снизу в тройные кавычки: ```

2021-05-11 14:42 UTC, vbagirov submitted a review, later dismissed

2021-05-11 14:46 UTC, sxgunchenko requested changes
А русский же тоже надо?

2021-05-11 15:26 UTC, vbagirov requested changes

2021-05-11 15:26 UTC, vbagirov commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> Отрицание `$redirect-rule` работает точно так же, как для обычных правил `$redirect`. Даже более того, `@@|||example.org^$redirect` будет отрицать как правило `$redirect`, так и `$redirect-rule`.
Давай тут везде "отрицание" заменим на "отмену"

2021-05-11 15:30 UTC, sxgunchenko commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> Отрицание `$redirect-rule` работает точно так же, как для обычных правил `$redirect`. Даже более того, `@@|||example.org^$redirect` будет отрицать как правило `$redirect`, так и `$redirect-rule`.
не успел :)

2021-05-11 15:30 UTC, slavaleleka requested changes

2021-05-11 15:30 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> Отрицание `$redirect-rule` работает точно так же, как для обычных правил `$redirect`. Даже более того, `@@|||example.org^$redirect` будет отрицать как правило `$redirect`, так и `$redirect-rule`.
`@@||example.org^$redirect` — то есть два символа `|`

2021-05-11 15:32 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +> Negating `$redirect-rule` works exactly the same way as for regular `$redirect` rules. Even more than that, `@@||example.org^$redirect` will negate both `$redirect` and `$redirect-rule rules`.
в конце `rules` вне кавычек наверное надо

2021-05-11 15:33 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +По сути, это тот же `$redirect`, поскольку у него тоже есть свойства "перенаправления" и логика у них практически аналогичная. Разница в том, что `$redirect-rule` применяется только в случае, если це
у нас в этой статье (и в многих других), увы, используются эти

2021-05-11 15:48 UTC, sxgunchenko approved these changes

2021-05-12 09:38 UTC, vbagirov approved these changes

2021-05-12 09:41 UTC, slavaleleka approved these changes

2021-05-12 09:41 UTC, merged