[AGM-871] Setting up system-wide ad blocking on iOS
AdguardTeam/AdguardKnowledgeBase pull request #818
Opened 2021-05-11 15:52 UTC by vbagirov

+ changed folder
+ moved the blog article with some changes

2021-05-11 16:01 UTC, el-termikael requested changes

2021-05-11 16:01 UTC, el-termikael commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ru
> +Вы можете добавлять любые DNS-фильтры или hosts-файлы, инструкция будет одинаковой для всех. Для примера давайте возьмём [фильтр AdGuard DNS](https://github.com/AdguardTeam/AdguardSDNSFilter). Он сос
1) Он составлен из нескольких других фильтров  (Базовый фильтр AdGuard — лишний пробел перед скобкой
2) оциальных сетей –> Фильтр социальных сетей
3) упрощён специально, чтобы иметь лучше блокировать рекламу на уровне DNS-запросов –> чтобы уметь? мб просто «чтобы иметь лучше блокировать рекламу»?

2021-05-11 16:01 UTC, el-termikael commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ru
> +> Важно: мы не рекомендуем трогать другие настройки в этом разделе, особенно *Низкоуровневые настройки*. Изменение некоторых из них может привести к проблемам с интернетом или скомпрометировать вашу
для для

2021-05-11 16:06 UTC, slavaleleka commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ru
> +Вы можете добавлять любые DNS-фильтры или hosts-файлы, инструкция будет одинаковой для всех. Для примера давайте возьмём [фильтр AdGuard DNS](https://github.com/AdguardTeam/AdguardSDNSFilter). Он сос
по третьему пункту:
https://kb.adguard.com/ru/general/adguard-ad-filters#filters
https://uploads.adguard.com/slbdzdr0ro03.png

2021-05-11 16:13 UTC, slavaleleka requested changes

2021-05-12 08:39 UTC, slavaleleka approved these changes

2021-05-12 12:38 UTC, ameshkov approved these changes

2021-05-12 14:34 UTC, merged