обновить overview для AdGuard для iOS
AdguardTeam/AdguardKnowledgeBase pull request #823
Opened 2021-05-17 09:42 UTC by el-termikael

2021-05-17 10:01 UTC, slavaleleka requested changes

2021-05-17 10:01 UTC, slavaleleka commented on 05.ios/01.overview/docs.en.md
> +    	* [DNS filtering](#dns-filtering)
может повыше поднять, сразу после днс-серверов?

2021-05-17 10:41 UTC, vbagirov requested changes

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> -AdGuard for iOS blocks ads on smartphones and tablets by Apple. AdGuard supports more than 50 filters optimized for Safari mobile browser, including a special filter for Russian websites.
Расширь title во 2 строчке

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +If you look for AdGuard in the App Store, you'll find two apps — [AdGuard](https://itunes.apple.com/us/app/id1047223162) and [AdGuard Pro](https://itunes.apple.com/ru/app/id1126386264). Don't be misl
вторая ссылка у тебя ведёт на ru

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +# Features
добавить бы сюда строчку буквально, совсем вкратце описав, какие функции есть

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> -AdGuard allows the user to fine-tune the settings: you can add any website to exceptions and stop blocking ads on it. You can also manually adjust every AdGuard filter, turn them on or off, or even c
Тут надо ещё добавить предложение типа "AG для iOS и AG Pro -- приложения, предназначенные для блокирования рекламы и трекинга в Safari и других приложениях, а также для управления DNS-защитой устройства"

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +Ad blockers' work is based on filters, also sometimes referred to as filter lists. Each filter is a list of filtering rules. If you have an enabled ad blocker when browsing, it constantly checks the
Только что мы их называли content blockers, а не ad blockers

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +To see the full list of filter categories (not to be confused with content blockers), go to *AdGuard for iOS Settings > Safari protection > Filters*.
Надо сначала рассказать, что фильтры объединены в категории по смыслу. А то из ниоткуда появился термин filter categories, так точно будет путаница

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +> Customs filter category is empty by default for users to add there filters by URL. You can find filters on the Internet or even try to [create one by yourself](https://kb.adguard.com/en/general/how
"Customs filter", "there" вместо "their" -- в общем тут несколько ошибок сразу

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +Assistant is a tool that helps you manage filtering right from Safari without switching back to the app. To see it, do the following: open Safari, tap on the arrow-in-a-box symbol. Then scroll down t
уточни, что речь именно про фильтрацию в Safari

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/ios_native_implementation.PNG" style="border: 1px solid #efefef; max-width: 300px; padding: 2px;">
у нас где-то 300px, где-то 400. Надо будет потом скриншоты привести все к единому образу

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +The native one has a slight advantage: the DNS is handled by the system and not the app. This means that AdGuard doesn't have to create a local VPN. Sadly, this will not help you circumvent system re
не надо писать, что есть преимущество. Могут подумать, что это более продвинутая опция, это не так. Скажи, что вот есть отличие

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +<p align="center"><i>Select a DNS server that suits your needs best</i><p>
Я думаю вообще убрать подписи к скринам, это не блог всё же. Может оставить только там, где подпись действительно привносит что-то новое в описание происходящего на скрине, но в большинстве случаев из текста рядом всё должно быть понятно

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +## DNS protection
нужна ссылка на статью в кб про DNS защиту

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +## DNS protection
Не в заголовок, а где-то в тексте

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +Similar to filters that work in Safari, DNS filters are sets of rules written according to special syntax. AdGuard will monitor your DNS traffic and block requests that match one or more rules. You c
ссыылка поменялась на https://kb.adguard.com/en/ios/solving-problems/how-to-configure-system-wide-blocking, замени пока редирект не сделан

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +> *DNS protection, Advanced mode, DNS filters* sum up to settings needed for system-wide blocking, i.e. blocking ads and trackers beyond the Safari browser, in other apps and browsers, on network lev
Я не очень понял эту фразу. Лучше убрать её и простым языком коротко объяснить, что вообще делают DNS фильтры и в чем отличие от обычных. А все детали по ссылке

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +Here AdGuard displays stats about user's DNS requests, such as total number, number of encrypted requests and average processing time. AdGuard can display the stats for a day, a week, a month, or in
лучше не user's, а device's. Приложения могут посылать (и шлют) запросы, о которых юзер не подозревает

2021-05-17 10:41 UTC, vbagirov commented on 05.ios/01.overview/docs.en.md
> +To open them, go to *Settings > General > Advanced settings > Low-level settings*. Mind that this section is only visible when Advanced mode is enabled. While some of these settings are better left i
Надо сильнее подчеркнуть, что не стоит сюда лезть, если не знаешь, что делаешь, или если поддержка не сказала так сделать

2021-05-17 14:48 UTC, el-termikael commented on 05.ios/01.overview/docs.en.md
> +    	* [DNS filtering](#dns-filtering)
ну в iOS на экране DNS protection они именно в такой последовательности

2021-05-17 14:59 UTC, el-termikael commented on 05.ios/01.overview/docs.en.md
> +> Customs filter category is empty by default for users to add there filters by URL. You can find filters on the Internet or even try to [create one by yourself](https://kb.adguard.com/en/general/how
хм, there и должно быть
разве что to add there their filters)

2021-05-18 17:16 UTC, vbagirov requested changes

2021-05-21 10:56 UTC, vbagirov requested changes

2021-05-21 10:56 UTC, vbagirov commented on 05.ios/01.overview/docs.ru.md
> +Блокировщики контента служат «контейнерами» для хранения правила фильтрации, которые и выполняют основную работу: блокируют рекламу и трекинг. В AdGuard для iOS шесть блокировщиков контента: General,
правил фильтрации

2021-05-21 10:56 UTC, vbagirov commented on 05.ios/01.overview/docs.ru.md
> +> Большее количество включенных фильтров не гарантирует, что рекламы будет меньше. Напротив, одновременные включенные фильтры способны снизить качество блокировки рекламы.
Вот эта фраза мне не нравится. Лучше убрать еёи заменить на "Имейте в виду, что одновременное включение большого количества фильтров может привести к выходу за лимит по правилам, и в некоторых редких случаях - к конфликтам между фильтрами"

2021-05-21 10:56 UTC, vbagirov commented on 05.ios/01.overview/docs.ru.md
> +Ещё один раздел экрана защиты Safari, который нуждается в представлении. Здесь вы можете добавить новые правила - либо введя их вручную, либо используя [инструмент ручной блокировки AdGuard в Safari]
имелось в виду "не нуждается"?

2021-05-21 10:56 UTC, vbagirov commented on 05.ios/01.overview/docs.ru.md
> +Помощник – это инструмент, который помогает (простите за каламбур) вам управлять фильтрацией прямо из Safari, не возвращаясь в приложение. Чтобы увидеть его, откройте браузер, нажмите на иконку короб
не надо про каламбуры в кб, наверное

2021-05-21 10:56 UTC, vbagirov commented on 05.ios/01.overview/docs.ru.md
> +## DNS-фильтрация
нужно тут хоть пару слов, что она делает

2021-05-21 10:56 UTC, vbagirov commented on 05.ios/01.overview/docs.ru.md
> +Чтобы открыть их, перейдите в *Настройки > Общие > Расширенные настройки > Низкоуровневые настройки*. Имейте в виду, что этот раздел доступен, только если включен Расширенный режим. Некоторые настрой
другие настройки можно настроить -- давай поменяем на "можно изменять" или как-то так

2021-05-21 12:16 UTC, vbagirov approved these changes

2021-05-21 12:35 UTC, slavaleleka approved these changes

2021-05-21 12:36 UTC, merged