Use `if-domain` and `unless-domain` together in Safari
AdguardTeam/AdguardKnowledgeBase pull request #824
Opened 2021-05-17 20:33 UTC by tvinzz

2021-05-18 09:58 UTC, el-termikael requested changes

2021-05-18 09:58 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>So the rules like `||baddomain.com^$domain=example.org|~foo.example.org` are invalid in AdGuard for Safari.
не хватает пробела после >

2021-05-18 09:58 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>So the rules like `||baddomain.com^$domain=example.org|~foo.example.org` are invalid in AdGuard for Safari.
и я бы 343 перенесла на одну строчку с 342

2021-05-18 09:58 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.en.md
> +>So the rules like `example.org,~foo.example.org##.textad` are invalid in AdGuard for Safari.
здесьь аналогично

2021-05-18 09:58 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> поэтому правила вида `||baddomain.com^$domain=example.org|~foo.example.org` в AdGuard для Safari яюляются невалидными.
поэтому правила вида `||baddomain.com^$domain=example.org|~foo.example.org` не действуют в AdGuard для Safari.
и тоже бы перенесла на одну строку

2021-05-18 09:58 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> поэтому правила вида `example.org,~foo.example.org##.textad` в AdGuard для Safari яюляются невалидными.
аналогично

2021-05-19 13:40 UTC, el-termikael requested changes

2021-05-19 13:40 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> **Важно!** Safari не поддерживает одновременно разрешенные и запрещенные домены, поэтому правила вида `||baddomain.com^$domain=example.org|~foo.example.org` в AdGuard для Safari яюляются невалидным
осталась правка одна неучтённая: 
поэтому правила вида `||baddomain.com^$domain=example.org|~foo.example.org` в AdGuard для Safari яюляются невалидными. —>
поэтому правила вида ||baddomain.com^$domain=example.org|~foo.example.org не действуют в AdGuard для Safari.

2021-05-19 13:40 UTC, el-termikael commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> **Важно!** Safari не поддерживает одновременно разрешенные и запрещенные домены, поэтому правила вида `example.org,~foo.example.org##.textad` в AdGuard для Safari яюляются невалидными.
same

2021-05-19 14:01 UTC, slavaleleka commented on 01.general/02.how-to-create-your-own-ad-filters/docs.ru.md
> +> **Важно!** Safari не поддерживает одновременно разрешенные и запрещенные домены, поэтому правила вида `||baddomain.com^$domain=example.org|~foo.example.org` в AdGuard для Safari яюляются невалидным
или вообще `не работают`

2021-05-20 10:22 UTC, el-termikael approved these changes

2021-05-27 23:14 UTC, merged