updated kb overview of AdGuard BE (RU)
AdguardTeam/AdguardKnowledgeBase pull request #866
Opened 2021-06-16 09:17 UTC by el-termikael

2021-06-16 12:22 UTC, vbagirov requested changes

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +В основном списке настроек AdGuard есть раздел *О программе*, где вы можете посмотреть, какую версию расширения вы используете. Здесь же вы найдёте ссылки на юридические документы, такие как Лицензио
"наш репозиторий" - как будто он один. Лучше "на репозиторий браузерного расширения"

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Здесь вы можете скрыть любой элемент на любой странице вручную (соответствующее правило будет добавлено в *Пользовательские правила*), открыть журнал фильтрации для просмотра информации о трафике ваш
"скрыть элемент на текущей странице" - чтобы избежать двоетолков

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Здесь вы можете скрыть любой элемент на любой странице вручную (соответствующее правило будет добавлено в *Пользовательские правила*), открыть журнал фильтрации для просмотра информации о трафике ваш
и опять объявления надо поменять

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Здесь вы можете скрыть любой элемент на любой странице вручную (соответствующее правило будет добавлено в *Пользовательские правила*), открыть журнал фильтрации для просмотра информации о трафике ваш
надо ещё подраздел про Журнал фильтрации, я думаю

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Кстати, у нас есть отдельное расширение для Safari, ведь с момента выхода [Safari 13](https://adguard.com/ru/blog/adguard-safari-1-5.html) большинство расширений столкнулись с огромными проблемами, и
Это выглядит как кусок, скопированный из блога или из соцсеток. Надо примерно то же самое написать более кбшным языком.

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +<a name="br-extension"></a>
Этот раздел я бы вообще поставил в самое начало статьи.

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +## Браузерное расширение AdGuard — Особенности применения
Думаю, можно просто оставить в качестве заголовка "Особенности применения" или даже просто "Особенности" или "Общие особенности"

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Расширение-блокировщик рекламы — очень удобный инструмент. Во-первых, вам не придётся тратить время на скачивание файлов и их установку. Во-вторых, расширение абсолютно бесплатно. В-третьих, после ус
Не надо использовать оценочные выражения типа "очень удобный инструмент". Может быть лучше вообще объединить этот кусок со следующим подразделом и просто написать "У браузерного расширения есть такие-то преимущества, но есть и такие-то недостатки в сравнении с десктопными приложениями. Вот сравнительная табличка. Если захотите подробнее почитать про приложения - вам сюда (дать ссылки на статьи про мак и винду)."

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Вторая существенная разница, как уже сказано выше, заключается в ограничении возможностей блокировки браузером. Расширения, блокирующие рекламу, всегда строго ограничены тем, что разрешено и не разре
Насчёт "многих" это преувеличения, я думаю. Ну и опять выражение, которое не очень подходит для блога, на мой взгляд: "не стоит и говорить"

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +`Хорошо*1 – в рамках возможностей браузера; действует только в браузере, в котором установлено расширение;`
Думаю, можно убрать "Хорошо" и "Средне" и просто оставить звездочки и циферки.

2021-06-16 12:22 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Надеемся, что данная таблица поможет вам выбрать тот способ борьбы с рекламой, который идеально подходит именно вам.
Эта фраза не нужна, по идее.

2021-06-16 13:40 UTC, el-termikael commented on 09.browser-extensions/01.overview/docs.ru.md
> +dGuard выпускает целый ряд продуктов для блокировки рекламы и трекеров на различных платформах. Одним из первых появилось браузерное расширение AdGuard, которое доступно для шести популярных браузеро
и всё-таки пять, а не четыре)) сафари просто убрала в последний момент

2021-06-17 11:27 UTC, vbagirov requested changes

2021-06-17 11:27 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Для браузера Safari у нас есть отдельное расширение, так как с момента выхода [Safari 13](https://adguard.com/ru/blog/adguard-safari-1-5.html) большинство расширений столкнулись с проблемами, и многи
Давай сделаем цитаткой (>), ну и ссылку лучше на овервью в кб, а не в блоге.

2021-06-17 11:27 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +**Однако не стоит забывать, что функциональность любого расширения строго ограничена возможностями самого браузера.** Поэтому, если вы заинтересованы в полноценной и всесторонней защите, обратите вни
Последняя фраза не в тему сейчас. Лучше изменить её немного и дать ссылку на правильный анкор.

2021-06-17 11:27 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +В данном разделе вы можете загружать фильтры, созданные другими людьми (в интернете их много [в открытом доступе](https://filterlists.com)) или добавлять свои. Фактически, вы можете создать любой наб
"созданные другими людьми в открытом доступе" - мне кажетя, как-то не очень звучит. 

В данном разделе вы можете добавить любые фильтры, которые отсутствуют в расширении по умолчанию. В интернете можно найти большое количество фильтров, находящихся в открытом доступе. Кроме того, вы можете создать и добавить свой собственный фильтр. Всё это обеспечивает максимальную гибкость в настройке блокировки так, как вам это нравится.

2021-06-17 11:27 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +Кроме того, здесь можно управлять модулем *Антифишинг*, включая/отключая *Защиту от фишинговых и вредоносных сайтов*. Вы также можете помочь в разработке антифишинговых фильтров, согласившись отправл
Там нет технических отчётов. Там статистика по тому, какие правила срабатывают на каких сайтах и как часто. Можно посмотреть в прайваси полиси, что именно пересылается.

"Приложение становитя лучше" - во-первых, расширение, а во-вторых, лучше становятся фильтры, а не оно :)

2021-06-17 11:27 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
> +### Сравнение расширений с полноценными приложениями
тут скорее всего надо `##`, а не `###`

2021-06-17 11:27 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.ru.md
>  Самым главным преимуществом приложений AdGuard является то, что они могут блокировать рекламу в каждом браузере и почти во всех приложениях. Вы можете использовать разные браузеры одновременно, прило
"Самым главным преимуществом приложений AdGuard перед браузерными расширениями" - наверное, так будет получше

2021-06-22 14:12 UTC, vbagirov requested changes

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +The Stealth mode can be flexibly adjusted — you can prohibit a website to receive the search requests you used to find it on the Internet, automatically delete both third-party and website’s own cook
Stealth Mode - имя собственное у нас

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +The Stealth mode can be flexibly adjusted — you can prohibit a website to receive the search requests you used to find it on the Internet, automatically delete both third-party and website’s own cook
И ссылку на `en` поменять

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +In case you want to keep your settings configuration, you can use the **Export settings** option to save it in a file. And vice versa, use the **Import settings** button to upload settings from a pre
save to a file?

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +In case you want to keep your settings configuration, you can use the **Export settings** option to save it in a file. And vice versa, use the **Import settings** button to upload settings from a pre
>You can even use to quickly switch between different settings profiles

use it?

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +Besides, here you can manage the *Browsing security* module by enabling or disabling the *Phishing and malware protection* and also opt to help us in the development of the security filters by sendin
Кстати да, эта настройка же в Misc, а не в General. Разберись, пожалуйста, и поправь что надо

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +`2 –  the extension is unable to detect requests from other extensions. So if some other, malicious or tracking extension wants to send a request to its server to show you ads or track your activity,
Уточнить в конце:

 the extension will not be able to block that request ->  AdGuard Browser extension will not be able to block that request

2021-06-22 14:12 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +    - [Allowlist](#whitelist)
А ещё у нас на всех скриншотах видно Whitelist сбоку, так что надо переделать

2021-06-23 14:32 UTC, vbagirov requested changes

2021-06-23 14:32 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +Then, it's possible to import a ready-to-use filter list from a text file. *Make sure that different rules are separated by line breaks.*  Besides, you can export filtering rules created by you. But
Section? Option имелось в виду?

2021-06-23 14:32 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +The Stealth Mode can be flexibly adjusted — you can prohibit a website to receive the search requests you used to find it on the Internet, automatically delete both third-party and website’s own cook
Всё ещё надо убрать "the"

2021-06-23 14:32 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +Besides, here you can manage the *Browsing security* module by enabling or disabling the *Phishing and malware protection* and also opt to help us in the development of filters by sending some anonym
Давай всё-таки сделаем тут нормально. Как такового модуля браузинг секурити тут нет, есть по сути только опция эта. Надо написать, что вот есть такой переключатель, вот он включает защиту от фишинга и малваря, вот тут подробно описано, что это такое: https://kb.adguard.com/en/general/how-malware-protection-works#other

И дальше ты рассказываешь про статистику по фильтрам в рамках подраздела про General, хотя она в miscellaneous.

2021-06-23 14:32 UTC, vbagirov commented on 09.browser-extensions/01.overview/docs.en.md
> +In case you want to keep your settings configuration, you can use the **Export settings** option to save it as a file. And vice versa, use the **Import settings** button to upload settings from a pre
>You can even use to quickly switch between different settings profiles

"You can even use it ..." имелось в виду?

2021-06-23 15:05 UTC, vbagirov approved these changes

2021-06-23 15:06 UTC, merged