GM-941 New article about features of Adguard VPN for iOS
AdguardTeam/AdguardKnowledgeBase pull request #877
Opened 2021-06-25 09:41 UTC by alim-shakirov

2021-06-25 09:46 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Captain Obvious: AdGuard VPN provides...VPN! And it has many benefits. First of all, our VPN allows to bypass geo-blocking of some websites by changing an IP adress. Secondly, it encrypts your traffi
AdGuard App может надо на AdGuardVpn App поменять, у нас еще просто есть приложение блокировщика которое называется AdGuard

2021-06-25 09:53 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Logging level: the default one and the extended one with more detailed logging
надо ли писать про лог левел? Этож больше не фича, а для разрабов инфа

2021-06-25 10:00 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Logging level: the default one and the extended one with more detailed logging
Возможно лучше написать про Diagnostic info, типа можно посмотреть актуальный айпи адрес и всякую другую инфу

2021-06-25 10:02 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +## Shortcuts
Шорткаты это немного другое, то про что ты пишешь называется Quick Actions, шорткаты мы пока не поддерживаем

2021-06-25 10:03 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +## Shortcuts
Share or Remove не нужно писать кажется, это стандартный функционал Quick action-ов, он у любой проги есть

2021-06-25 10:04 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* 5 devices with enabled AdGuard VPN (there can be more devices overall, but only five can be used simultaneously)
Точно 5 в бесплатном, кажется 2 было

2021-06-25 10:05 UTC, 08kovalchuk03 commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Accordingly, the paid version offers unlimited traffic and speed, yet the number of devices stays the same. So enjoy the boundless web surfing with AdGuard VPN for iOS!
Может лучше наоборот выделить премиум фичи в список?

2021-06-25 13:50 UTC, vbagirov requested changes

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Captain Obvious: AdGuard VPN provides...VPN! And it has many benefits. First of all, our VPN allows to bypass geo-blocking of some websites by changing an IP adress. Secondly, it encrypts your traffi
Ну и вообще в таком вступительном параграфе хорошо будет смотреться краткое описание того, для чего нужен АГ ВПН вообще - ты говоришь про это, но мне кажется надо чуть более акцентированно: Адгард ВПН нужен для того-то и того-то, помогаем с тем-то. Можно где-то добавить фразу про то, что подробнее можно узнать про то, как работает впн, из отдельной статьи (её пока нет, но потом добавим ссылку туда).

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +## VPN itself
Заголовок странный, логичнее будет смотреться что-то в духе "What is AdGuard VPN" или "What AdGuard VPN does" или как-то так. Анкор тоже соответствующим образом поменять лучше.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +AdGuard VPN for iOS has two exclusion lists — for Regular and Selective Modes. It can work either on all websites except those added to exclusions, or only on websites added to exclusions. You can ad
1. Лучше начать с того, где вообще это всё находится (средняя кнопка в нижнем ряду). Затем перейти к тому, что вот есть два режима, вот так они устроены, такие отличия. Затем перейти уже непосредственно к списку исключений - он сам по себе органично вытечет из описания режимов.

2. `*.google.com` а не `*google.com`, кажется

3. Мы стараемся не давать ссылки из кб на блог по возможности. Чаще наоборот. Если в блоге есть какая-то инструкция, лучше перенести её в базу знаний. Не зря она называется "база знаний" - тут по идее должно быть собрано всё, что касается продуктов и их функционала.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +<a name="lists-of-exclusions"></a>
Анкоры не обязательно называть дословно так же, как и заголовки. Достаточно просто коротко и по смыслу: `#exclusions`, например. Не то чтоб это косяк, просто так проще потом будет всем

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Operating mode: the general one uses AdGuard VPN own protocol, the integrated one allows AdGuard VPN and AdGuard ad blocker to work together by using IPSec protocol
Про оперейтинг мод можно отдельный заголовок, всё-таки это довольно большая фича. Надо подчеркнуть, что ВПНы как правило не работают с другими впн-приложениями, а вот Адгард ВПН может работать с блокировщиком Адгард. Описать, как настроить интеграцию (по сути просто включить соответствующий режим, но может есть нюансы - я не знаю). Также надо рассказать, какие ограничения есть. Я тоже не знаю точно какие, но как минимум исключения не будут работать.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* DNS server: you can choose one of 10 differnt DNS servers by AdGuard, Google, Cloudflare and more
Нужно коротко рассказать, что такое DNS сервер вообще, дать ссылку на нашу статью, где написано что такое днс (https://kb.adguard.com/en/general/dns-filtering#what-is-dns). И лучше не писать "один из 10", потому что можем потом добавить новые, например. Просто сказать "один из предлагаемых по умолчанию популярных и надёжных днс-серверов".

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can configure Adguard VPN for iOS as you need by selecting different options:
Нужно упомянуть, где все эти настройки находятся.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Theme: system default, dark or light
Уточни, на старых девайсах похоже нет такой опции.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Captain Obvious: AdGuard VPN provides...VPN! And it has many benefits. First of all, our VPN allows to bypass geo-blocking of some websites by changing an IP adress. Secondly, it encrypts your traffi
Ещё надо рассказать здесь или в отдельном подразделе про главный экран. Что там есть кнопка Connect/Disconnect, что есть список локаций, что означают цифры рядом с локациями.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Diagnostic info: locally stored technical information about the device and connections (IP addess, ID, Ping, etc.)
Здесь надо подчеркнуть, что всё внутри адвансед сеттингс (включая логгинг левел, про который ты говоришь только очень вскользь дальше) вообще лучше особо не трогать, если вас специально не попросила поддержка или если вы не уверены на 100% в том, что делаете.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +## Quick Actions
То же чето на старом девайсе не получилось повторить, уточни у разрабов - я криворукий или не поддерживается.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The users' accomplishment is the high priority for us. So there is a variety of helping features in the app: you can see the FAQ section, report a bug, leave a feedback, discuss on our forum, in soci
Надо рассказать, где можно найти все эти опции.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The users' accomplishment is the high priority for us. So there is a variety of helping features in the app: you can see the FAQ section, report a bug, leave a feedback, discuss on our forum, in soci
Ещё нужно сделать подраздел про то, как активировать премиум. Может быть, начать с этого раздел про unlimited версию, но в общем нужно, чтобы эта информация была.

2021-06-25 13:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +## More features in the unlimited version!
У нас будет отдельная статья про преимущества платной подписки, надо заложиться на это и где-то включить ссылку на неё. Ну точнее пока просто плейсхолдер под ссылку.

2021-06-28 10:07 UTC, el-termikael requested changes

2021-06-28 10:07 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +4. Open AdGuard VPN on the device/in the browser where you want to export the archive with the ready lists of exclusions. Find the appropriate section, click on the "Import" button and select the arc
и тут кавычки

2021-06-28 10:07 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +1. Operating mode: the general one uses AdGuard VPN own protocol, the integrated one allows AdGuard VPN and AdGuard ad blocker to work together by using IPSec protocol
general и integrated лучше с большой

2021-06-28 10:07 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +2. [DNS](https://kb.adguard.com/en/general/dns-filtering#what-is-dns) (Domain name system) server. Its purpose is to translate websites' names into something browsers can understand, i.e. IP addresse
, etc. —> or other providers

2021-06-28 10:07 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +5. Diagnostic info: locally stored technical information about the device and connections (IP addess, ID, Ping, etc.). You can use this information in case of any technical problems by sending it to
addess
ping и support с маленькой

2021-06-28 10:07 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can read more about the benefits of the paid version in this arcticle.
не хватает ссылки опять же

2021-06-28 10:53 UTC, vbagirov requested changes

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +A VPN allows you to create a secure connection to another network on the Internet. It connects a user's computer or mobile device to a server and allows one to browse the net using someone else's IP
Статьи пока нет, потом добавим все ссылки

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> + The next advantage of AdGuard VPN for iOS is our own VPN protocol, the reliable feature for uncompromised security. And, of course, there is a wide range of the lightning-fast servers. How many exac
Я вообще считаю, что надо фразу поменять. Она снова получилась маркетинговой какой-то, а не кбшной.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +<a name="exclusions"></a>
Тут какое-то несоответствие анкора и заголовка

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Using AdGuard VPN is quite easy. In the main screen you can see the Connect/Disconnect button and the lists of available servers. There servers have their own location (the certain country and the ci
In the main screen -> On the main screen

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Using AdGuard VPN is quite easy. In the main screen you can see the Connect/Disconnect button and the lists of available servers. There servers have their own location (the certain country and the ci
Скорость не может быть в милисекундах, корректнее использовать термин типа "response time". Можно для ясности потом добавить, что чем ниже пинг, тем выше скорость.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Using AdGuard VPN is quite easy. In the main screen you can see the Connect/Disconnect button and the lists of available servers. There servers have their own location (the certain country and the ci
Лучше не писать точные цифры, которые потом придется обновлять. Over 50 locations in dozens of countries - так будет лучше.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can find exclusion feature by tapping the middle button below. Then you will see two exclusion lists — for Regular and Selective Modes. In the first list you can add those websites on which AdGua
Всё ещё логики недостает. Добавь прям фразу "В Regular режиме впн работает везде, кроме сайтов из списка исключений, а в Selective режиме - наоборот, впн работает только на сайтах из списка". Простая фраза, которая сразу объясняет, в чем отличие двух режимов. А дальше уже продолжаешь про домены, поддомены и т.д.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Another useful feature is the import/export of exclusion lists.  It can work either on all websites except those added to exclusions, or only on websites added to exclusions. You can add domains (e.g
Здесь повторяется текст из предыдущего абзаца.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can find exclusion feature by tapping the middle button below. Then you will see two exclusion lists — for Regular and Selective Modes. In the first list you can add those websites on which AdGua
И ещё, `google.com` и `*.google.com` лучше выделить как code через такие кавычки: `

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +1. Open AdGuard VPN on the device/in the browser from where you want to export your lists of exclusions. Find the appropriate section and click on the "Export" button. The exclusions.zip archive will
Можно выделять названия кнопок *Курсивом* и с большой буквы

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +1. Open AdGuard VPN on the device/in the browser from where you want to export your lists of exclusions. Find the appropriate section and click on the "Export" button. The exclusions.zip archive will
`exclusions.zip` тоже можно в code обернуть. Ну и вообще подобные вещи лучше так выделять для лучшего ридабилити

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +2. There are two TXT files inside the archive, each for Regular and Selective lists. Add more exclusions to them, delete the existing ones, rename files (but more on this later), or just leave the ar
each for -- наверное имелось в виду "one for each of Regular and Selective lists"?

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +2. There are two TXT files inside the archive, each for Regular and Selective lists. Add more exclusions to them, delete the existing ones, rename files (but more on this later), or just leave the ar
leave as it is -> leave as is. 
Наверное это не ошибка, но так вроде будет получше звучать

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +3. When transferring between different devices, don't forget to send the zip file to the device for import. For example, if you import exclusion lists from your Android device to your PC, make sure t
Во 2 пункте было `TXT`, а тут `zip` - надо привести к единому формату. Может быть, лучше всего сделать так: `.zip`, `.txt`

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +3. When transferring between different devices, don't forget to send the zip file to the device for import. For example, if you import exclusion lists from your Android device to your PC, make sure t
Не очень понятно, почему тут пример с андроидом и пк, если у нас статья про иос. Пусть будет экспорт с мака на иос, например - это более реалистичный сценарий.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +4. Open AdGuard VPN on the device/in the browser where you want to export the archive with the ready lists of exclusions. Find the appropriate section, click on the "Import" button and select the arc
Опять же, если статья про иос, то наверное браузер тут не нужен.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +1. Operating mode: the general one uses AdGuard VPN own protocol, the integrated one allows AdGuard VPN and AdGuard ad blocker to work together by using IPSec protocol
Проигнорировал мои комментарии про оперейтинг мод из предыдущего ревью

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can configure Adguard VPN for iOS as you need by selecting different options:
Предыдущий комментарий проигнорирован.

AdGuard пишем с заглавной G

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +2. [DNS](https://kb.adguard.com/en/general/dns-filtering#what-is-dns) (Domain name system) server. Its purpose is to translate websites' names into something browsers can understand, i.e. IP addresse
В целом лучше, но всё ещё надо улучшить эту часть. Как с точки зрения форматирования, так и с точки зрения информации. Пингани меня, я напишу, как вижу этот кусочек.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +5. Diagnostic info: locally stored technical information about the device and connections (IP addess, ID, Ping, etc.). You can use this information in case of any technical problems by sending it to
Опять не учел мой комментарий из предыдущего ревью.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +To access this feature, touch and hold the app icon, then lift your finger. You'll see a list of Quick Actions: Connect, Choose location, Edit Home Screen. Choose the one you need and AdGuard will re
Лучше расписать как-нибудь, типа 
"You'll see a list of Quick Actions: *Connect*/*Disconnect* to the currently selected server, *Choose location* to select a new server location. You can also, of course, access all default actions like removing the app or moving the app icon around".

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The users' accomplishment is the high priority for us. So there is a variety of helping features in the app: you can see the FAQ section, report a bug, leave a feedback, discuss on our forum, in soci
Проигонированы комментарии предыдущего ревью.

2021-06-28 10:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +## More features in the unlimited version!
Пригнорирован комментарий из предыдущего ревью.

2021-06-28 14:57 UTC, el-termikael requested changes

2021-06-28 14:57 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can use the General mode with AdGuard VPN own protocol which provides the best combination of speed and security. While VPN usually can't interact with other VPN and ad blocking apps, the Integra
While VPN usually can't interact with other VPN and ad blocking apps — > While VPN apps usually can't interact with other VPN and ad blocking apps

2021-06-28 14:57 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The purpose of Domain name system (DNS) is to translate websites' names into something browsers can understand, i.e. IP addresses. AdGuard VPN for iOS offers DNS servers with different fuctions. For
You can choose DNS server —>  You can choose a DNS server

2021-06-28 14:57 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Unlimited traffic *vs.* 3 GB of traffic
3 GB per month

2021-06-28 15:50 UTC, vbagirov requested changes

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +
Здесь абзац про протокол пропал. Я просил переписать, а не удалить совсем. Если есть сложности или вопросы, как это лучше сделать, спрашивай.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Using AdGuard VPN is quite easy. On the main screen you can see the *Connect/Disconnect* button and the lists of available servers. There servers have their own location (a certain country and a city
Lists - список вроде один?

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Using AdGuard VPN is quite easy. On the main screen you can see the *Connect/Disconnect* button and the lists of available servers. There servers have their own location (a certain country and a city
Эту фразу можно упростить:

>The ping describes a response time (in milliseconds) of data submission between a user's device and a server:

The ping describes the response time of the server (in milliseconds). 

>ping of 22 ms means that information from the device will reach this server in 22 milliseconds

На самом деле это время, через которое сервер уже ответит обратно.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can find the exclusion feature by tapping the middle button below. Then you will see two exclusion lists — for Regular and Selective Modes. In the Regular mode the VPN works on all websites excep
Then you will see two exclusion lists -> There you will see two exclusion lists

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +4. Open AdGuard VPN on the device where you want to export the archive with the ready lists of exclusions. Find the appropriate section, click on the *Import* button and select the archive.
>Open AdGuard VPN on the device where you want to export the archive

Import имелось в виду? Мы же импортируем на последнем шаге.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can use the General mode with AdGuard VPN own protocol which provides the best combination of speed and security. While VPN usually can't interact with other VPN and ad blocking apps, the Integra
```
AdGuard VPN for iOS can operate in two modes: **General** and **Integrated**.

In **General** mode, the [AdGuard VPN protocol](#adguard-vpn) is employed, which provides the best combination of speed and security. In this mode, AdGuard VPN will not be able to work alongside [AdGuard for iOS ad blocker](https://kb.adguard.com/en/ios).

In **Integrated** mode, AdGuard VPN will be able to work at the same time with AdGuard for iOS ad blocker by using the IPSec protocol instead. This protocol is also secure, but a little slower and easier to detect. You don't need to perform any additional actions to set up the integration: just install both apps and switch to this mode.

>Note that in **Integrated** mode you can't use the Exclusions feature or choose a DNS server.
```

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The purpose of Domain name system (DNS) is to translate websites' names into something browsers can understand, i.e. IP addresses. AdGuard VPN for iOS offers DNS servers with different fuctions. For
Давай такое предложение добавим между 1 и 3 предложениями:

This job is performed by DNS servers.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The purpose of Domain name system (DNS) is to translate websites' names into something browsers can understand, i.e. IP addresses. AdGuard VPN for iOS offers DNS servers with different fuctions. For
AdGuard VPN for iOS offers DNS servers with different fuctions. -> AdGuard VPN for iOS offers a choice between several DNS servers, each with their own special qualities.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The purpose of Domain name system (DNS) is to translate websites' names into something browsers can understand, i.e. IP addresses. AdGuard VPN for iOS offers DNS servers with different fuctions. For
You can choose DNS server not only depending on its functions but also on its provider: there are the DNS servers by AdGuard, Google, Cloudfare and some others. -> DNS servers by different DNS providers may also work faster or slower depending on your location, ISP, and other factors. Choose the one that works best for you.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +In the *Advanced settings* you can find two sections - Logging level and Diagnostic info. Concerning the first option it is not recommended to enable the Extended logging level unless required by our
Мы используем длинные тире: —

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +In the *Advanced settings* you can find two sections - Logging level and Diagnostic info. Concerning the first option it is not recommended to enable the Extended logging level unless required by our
unless required by our support team -> unless requested by our support team

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +*   [Support](#support)
В статье разделы support и quick actions идут в другом порядке, тут тоже надо поменять

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The users' accomplishment is the high priority for us. So there is a variety of helping features in the app (press the *Settings* button bottom right and then *Support*): you can see the FAQ section,
press the *Settings* button bottom right and then *Support* -- пропущен предлог, видимо

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +* Unlimited traffic *vs.* 3 GB of traffic
per month надо добавить

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can read more about the license and its features [in this arcticle](link).
Там не столько про лицензию и её свойства, сколько про различия между платной и бесплатной версиями. Надо чуть-чуть перефразировать.

2021-06-28 15:50 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +
Вот тут надо отдельным абзацем рассказать, что необходимо залогиниться, чтобы пользоваться Адгард ВПН. Надо рассказать про личный кабинет и про логин через соцсетки.

2021-06-28 17:30 UTC, vbagirov requested changes

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The next advantage of AdGuard VPN for iOS is our own VPN protocol. It helps to combine the App with our another app - AdGuard Ad Blocker and saves high connection speed while encrypting your traffic.
Прочитай статью про протокол и перепиши эту часть, там другие преимущества.

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The next advantage of AdGuard VPN for iOS is our own VPN protocol. It helps to combine the App with our another app - AdGuard Ad Blocker and saves high connection speed while encrypting your traffic.
Мы используем длинные тире: —

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Before using AdGuard VPN for iOS, you need to pass authorization. Your can sign in via your Facebook or Google account, Apple ID or by creating an AdGuard account.
Здесь тоже есть нюанс: если ты логинишься через гугл, эппл или фб, то у тебя на эту же почту должен быть зарегистрирован Адгард аккаунт. Просто экономия времени, чтобы не вспоминать почту и пароль от Адгарда. Упомяни, что если Адгард аккаунта нет, то создать придётся в любом случае.

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Using AdGuard VPN is quite easy. On the main screen you can see the *Connect/Disconnect* button and the list of available servers. There servers have their own location (a certain country and a city)
Ну только не information will turn back, а что-то вроде "... that the signal will reach the server and return back in 22 milliseconds"

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The purpose of Domain name system (DNS) is to translate websites' names into something browsers can understand, i.e. IP addresses. This job is performed by DNS servers. AdGuard VPN for iOS offers a c
Adguard DNS Family -> AdGuard DNS Family

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The users' accomplishment is the high priority for us. So there is a variety of helping features in the app (press the *Settings* button in the bottom right and then *Support*): you can see the FAQ s
Если `in`, то "in the bottom right corner", либо "at the bottom right"

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can buy a license of AdGuard VPN to get the unlimited version of the App. In the *Settings* choose *About license* and press the *Manage* button. You will be sent to the browser page where you ca
Я не обратил внимания, у нас же "AdGuard VPN subscription", а не license. Надо поменять везде в тексте, где встречается (кроме *About License*).

2021-06-28 17:30 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +*   [App settings](#settings)
Я подумал, тут наверное можно добавить вложенный список со ссылками на подпункты (`#dns-server` и всё такое). И не забыть анкоры рядом с самими подпунктами.

2021-06-29 10:31 UTC, vbagirov requested changes

2021-06-29 10:31 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +The next advantage of AdGuard VPN for iOS is our own VPN protocol. It has two main benefits: comparing to other VPN protocols it is extremely hard to detect and it works stably even with a poor Inter
Норм, только давай зашьем сюда гиперлинк на будущую статью про протокол AdGuard VPN.

2021-06-29 10:31 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +Before using AdGuard VPN for iOS, you need to pass authorization. Your can sign in via your Facebook or Google account, Apple ID or by creating an AdGuard account. If you don't have an AdGuard accoun
Всё ещё не то, что я просил. Давай так:

```
To use AdGuard VPN for iOS, first you need to log into your [AdGuard account](https://my.adguard.com/). You can sign in directly with your AdGuard account credentials, or via Google, Apple ID, or Facebook (if your AdGuard account was registered using the same email address).

If you don't have an AdGuard account yet, you will have to create it first.
```

2021-06-29 10:31 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/010.features-overview/docs.en.md
> +You can buy a license of AdGuard VPN to get the unlimited version of the App. In the *Settings* choose *About license* and press the *Manage* button. You will be sent to the browser page where you ca
Проигнорировано опять.

2021-06-29 15:05 UTC, vbagirov approved these changes

2021-06-29 15:19 UTC, vbagirov commented
Duplicate for #880

2021-06-29 15:20 UTC, closed without merging