AGM-951 AdGuard VPN for Mac overview
AdguardTeam/AdguardKnowledgeBase pull request #884
Opened 2021-07-05 10:24 UTC by el-termikael

2021-07-05 12:44 UTC, vbagirov requested changes

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +AdGuard VPN for Mac is a desktop VPN service. It is currently in the beta stage, but it doesn’t mean that the app is raw. Quite the opposite, it is working stable and can be used. AdGuard VPN is full
and can be used - напрашивается уточнение, как именно: полноценно или смело или как-то ещё

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +
Table of Contents нужна

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +The first tab is the *Home* screen. Here you can see AdGuard VPN current status and [operating mode](https://kb.adguard-vpn.com/en/mac-vpn/features-overview#exclusions), chosen location (if enabled)
ссылку поправить

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +> Free users can connect only to certain locations, while others are blocked. Besides, there is a 3GB monthly traffic limit in the free version.
Предлагаю помимо такого упоминания сделать отдельный раздел в конце статьи, где перечислить все отличия платной версии от бесплатной и дать ссылку на статью про различия. 

Кстати в макверсии точно есть бесплатный режим?

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +What’s more, ready-made exclusions lists can be transferred to other devices with the installed AdGuard VPN. [Learn how to export or import exclusions](https://adguard.com/en/blog/import-export-adgua
Надо инструкцию явно написать здесь, а ссылку на блог можно убрать.

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +The third tab is the *Support* screen. Find answers to any questions in the [FAQ](https://adguard-vpn.com/en/welcome.html#faq) or in the [Knowledge base](https://kb.adguard-vpn.com/en) sections, repo
Можно не писать, что ровно 6, кто знает что там поменяется потом

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Finally, we come to the most important tab — Settings. In the *About program* section you can see the current version of AdGuard VPN, check for updates, visit our official website, and get acquainted
Не знаю, где ещё оставить этот комментарий -- нам надо рассказать, что приложением нельзя пользоваться, не залогинившись в ЛК адгард. А также расписать, какие способы логина есть (в каком случае можно будет залогиниться через гугл/фб, например) и что будет, если в ЛК, в который логинишься, есть активная подписка.

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Finally, we come to the most important tab — Settings. In the *About program* section you can see the current version of AdGuard VPN, check for updates, visit our official website, and get acquainted
В статье про AG VPN для iOS мы, например, в самом начале статьи говорим про это, потому что без этого вообще нельзя пользоваться приложением.

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Advanced settings are also known as low-level ones. They are encouraged to be adjusted by users with solid technical knowledge/background.
Это фраза мне не нравится совсем. 

1) Точно адвансед и low-level настройки - это одно и то же на маке? Во многих других наших продуктах, например, это не так.

2) Мы точно не призываем никого их менять. Скорее наоборот, призываем туда не лезть вообще, если только не попросила поддержка или если пользователь не уверен на 100%, что делает.

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +There are only two logging levels but we strongly recommend that you use the first, default one. The second option (extended logging) should be set only to record a strange program behavior after con
Также упомянуть, что если даже включаете его, то после записи лога обязательно выключайте обратно

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Basically, that’s it. Another thing you should know is that AdGuard VPN for Mac is currently supported on Catalina and Big Sur. The support for older versions of macOS will be available shortly.
Можно эту фразу убрать, она звучит как из блога взятая. А информацию про то, в каких версиях macOS работает, можно включить во вступительную часть.

2021-07-05 12:44 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +There are only two logging levels but we strongly recommend that you use the first, default one. The second option (extended logging) should be set only to record a strange program behavior after con
Ещё надо сказать, откуда можно экспортировать записанные логи в файл.

2021-07-06 10:28 UTC, vbagirov requested changes

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +> Note that **you can't use AdGuard VPN for Mac unless you have logged into your AdGuard account**. You can either sign in with your AdGuard account or with an external account, namely, via Google or
Думаю здесь block quote можно убрать.

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +* [Exclusions](#content-blockers)
тут что-то не так с ToC, откуда-то `content blockers` взялись, а `exclusions` например не хватает. Поправь

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +1. Open AdGuard VPN on the device/in the browser from where you want to export your lists of exclusions. Find the appropriate section and click on the *Export* button. The `exclusions.zip` archive wi
Наверное раз речь про AG VPN для Mac, то не в браузере.

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +What’s more, ready-made exclusions lists can be transferred to other devices with the installed AdGuard VPN. To export exclusions, follow the four-step instruction below:
the кажется лишним

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +2. There are two TXT files inside the archive, each for Regular and Selective lists. Add more exclusions to them, delete the existing ones, rename files (but more on this later), or just leave the ar
Думаю, лучше "`.txt` files" или "text files"

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +3. When transferring between different devices, don't forget to send the zip file to the device for import. For example, if you import exclusion lists from your Android device to your PC, make sure t
`.zip` вместо zip

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +3. When transferring between different devices, don't forget to send the zip file to the device for import. For example, if you import exclusion lists from your Android device to your PC, make sure t
Непонятно, причем тут перенос исключений с Android на PC, если статья про мак

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> + * Email clients can be used for sending messages (for AdGuard VPN for iOS and Android)
Этот пункт очевидно не нужен в статье про AG VPN для Mac

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> + * Email clients can be used for sending messages (for AdGuard VPN for iOS and Android)
Зато нужно оставить где-то тут ссылку на статью про преимущества платной версии. Опять же, урла пока нет, поэтому просто плейсхолдер

2021-07-06 10:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +> The last point should be addressed separately: users of the free version of AdGuard VPN for iOS and Android cannot send emails in email clients. It’s impossible because we block port 25, which is u
Это здесь тоже не нужно, статья про мак

2021-07-06 10:57 UTC, vbagirov requested changes

2021-07-06 10:57 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +* [Filters](#filters)
всё ещё лишние пункты какие-то

2021-07-06 10:57 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +2. There are two .txt files inside the archive, each for Regular and Selective lists. Add more exclusions to them, delete the existing ones, rename files (but more on this later), or just leave the a
Давай сделаем такое форматирование: `.txt`, так будет чуть лучше смотреться. И `.zip` тоже везде по тексту.

2021-07-06 10:57 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +What’s more, ready-made exclusions lists can be transferred to other devices with installed AdGuard VPN. To export exclusions, follow the four-step instruction below:
Наверное ещё тогда надо рассказать, как импортировать тоже. Может не отдельной инструкцией, но может в каком-то из пунктов упомянуть, что можно эти файлы архивов, полученные с других девайсов, импортировать в ваш AG VPN для Mac. Или не в пункте, а просто после инструкции.

2021-07-06 11:39 UTC, harry-b commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +The first tab is the *Home* screen. Here you can see AdGuard VPN current status and [operating mode](#exclusions), chosen location (if enabled) and its ping. The fastest locations with the lowest pin
можно добавить, что в левом нижнем углу - отображается последняя локация, к торой подключались

2021-07-06 11:45 UTC, harry-b commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Note that **you can't use AdGuard VPN for Mac unless you have logged into your AdGuard account**. You can either sign in with your AdGuard account or with an external account, namely, via Google or F
помимо AdGuard - Apple, Facebook, Google

2021-07-06 12:03 UTC, el-termikael commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Note that **you can't use AdGuard VPN for Mac unless you have logged into your AdGuard account**. You can either sign in with your AdGuard account or with an external account, namely, via Google or F
https://uploads.adguard.com/el.termikael4tydj.png про Google и Facebook написала, а через Apple как? sign up with email address?

2021-07-06 12:21 UTC, harry-b commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Note that **you can't use AdGuard VPN for Mac unless you have logged into your AdGuard account**. You can either sign in with your AdGuard account or with an external account, namely, via Google or F
Sign with Apple ID

2021-07-06 12:27 UTC, el-termikael commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Note that **you can't use AdGuard VPN for Mac unless you have logged into your AdGuard account**. You can either sign in with your AdGuard account or with an external account, namely, via Google or F
не вижу такой опции в интерфейсе

2021-07-06 12:56 UTC, harry-b commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.en.md
> +Note that **you can't use AdGuard VPN for Mac unless you have logged into your AdGuard account**. You can either sign in with your AdGuard account or with an external account, namely, via Google or F
<img width="912" alt="Screenshot 2021-07-06 at 15 19 25" src="https://user-images.githubusercontent.com/1119809/124603557-b6d54400-de72-11eb-86a0-1c747f74b8d8.png">

2021-07-06 15:05 UTC, vbagirov requested changes

2021-07-06 15:05 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.ru.md
> +Третья вкладка — это экран *Поддержка*. Найдите ответы на любые вопросы в [FAQ](https://adguard-vpn.com/ru/welcome.html#faq) или [Базе знаний](https://kb.adguard-vpn.com/ru), сообщите об ошибке, если
Ссылка на базу знаний неправильная, надо https://kb.adguard.com/ru/vpn. В англ тоже не обратил внимания, там надо https://kb.adguard.com/en/vpn

2021-07-06 15:05 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.ru.md
> +Третья вкладка — это экран *Поддержка*. Найдите ответы на любые вопросы в [FAQ](https://adguard-vpn.com/ru/welcome.html#faq) или [Базе знаний](https://kb.adguard-vpn.com/ru), сообщите об ошибке, если
Не уверен насчёт "не забывайте оставлять отзывы", немного агрессивно на мой взгляд звучит

2021-07-06 15:05 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/010.overview/docs.ru.md
> +Ещё одна опция, которую не стоит обходить вниманием — вы можете разрешить AdGuard VPN собирать и отправлять анонимизированные отчёты о сбоях и технические данные, чтобы помочь нам улучшить наше прило
Наверное, стоит сказать, что экспорт логов может быть полезен, если вы хотите прикрепить их к сообщению в поддержку.

2021-07-06 16:32 UTC, vbagirov approved these changes

2021-07-07 08:40 UTC, merged