[AGM 952] new article how vpn works
AdguardTeam/AdguardKnowledgeBase pull request #887
Opened 2021-07-06 14:50 UTC by alim-shakirov

2021-07-06 15:12 UTC, el-termikael requested changes

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +VPN создает между вашим девайсом и VPN-сервером своеобразный туннель, в котором ваши данные зашифровываются и уже затем в защищенном виде попадают в открытый интернет. Поэтому вашим данным будет прис
созда**ё**т
в защищ**ё**нном виде

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +1. *Протокол туннелирования второго уровня (англ. Layer 2 Tunneling Protocol или L2TP/IPSec)*. L2TP – это VPN-протокол, который не шифрует данные сам, а использует для этого другой протокол [IPSec](h
к более медленной скорости соединения —>  к более низкой скорости соединения /  к более медленному соединению

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +2. *Уровень защищённых сокетов (SSL)* и *Протокол защиты транспортного уровня (TLS)*. До 2014 года SSL часто использовался для шифрования данных в электронной почте и интернет-факсе, для обмена мгнов
над**ё**жную

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +3. *Протокол безопасного туннелирования сокетов (SSTP)*. Этот протокол разработан Microsoft и считается безопасным и простым в использовании. Один из немногих его минусов - в отличие от работы на Win
в отличие от работы на Windows, его работоспособность может уменьшаться на других операционных системах — наверное, здесь лучше подходит слово «производительность». и в целом хорошо бы переформулировать

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +6. *WireGuard*. Протокол работает еще быстрее и стабильнее, чем OpenVPN и IKEv2.
ещ**ё**

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие ресурсы, в том числе сайты, стриминговые сервисы и онлайн-платформы, доступны лишь в определенных странах. VPN меняет вашу виртуальную локацию и помогает обойти геоблокировку.
определ**ё**нных

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие ресурсы, в том числе сайты, стриминговые сервисы и онлайн-платформы, доступны лишь в определенных странах. VPN меняет вашу виртуальную локацию и помогает обойти геоблокировку.
VPN меняет вашу виртуальную локацию — вот эта формулировка не нравится
и помогает обойти геоблокировку — хорошо бы обозначить, что это такое

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +При подключении к ненадежной или общедоступной сети данные на вашем устройстве могут стать уязвимыми для киберпреступников. VPN-туннель шифрует информацию, которую вы отправляете и получаете из сети,
ненад**ё**жной
чужиие

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +На скорость интернет-соединения при использовании VPN влияют несколько факторов: удаленность VPN-сервера от вашего настоящего местоположения, загруженность VPN-сервера, его пропускная способность, со
удал**ё**нность

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Даже самые надежные VPN-провайдеры не гарантируют вам бесперебойного соединения. Слабый сигнал, перегруженность сети, несовместимость VPN с брандмауэром, антивирусом и другими программами, устаревший
над**ё**жные
вс**ё** это

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Так как  VPN позволяет сохранить анонимность и уйти от онлайн-слежки, в том числе государственной, в некоторых странах использование VPN запрещено законом.
лишний пробел перед VPN

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Так как  VPN позволяет сохранить анонимность и уйти от онлайн-слежки, в том числе государственной, в некоторых странах использование VPN запрещено законом.
ну и страны можно перечислить, хотя бы несколько
но надо ещё добавить, что в большинстве стран использование VPN (в легитимных целях) вполне легально

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Наш  VPN-сервис имеет несколько важных преимуществ:
опять лишний пробел после «Наш»
Наш  VPN-сервис имеет несколько важных преимуществ: —> Наш  VPN-сервис обладает несколькими важными преимуществами / У нашего VPN-сервиса есть несколько важных преимуществ

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* *политика «без логов»*, которая означает, что AdGuard VPN не собирает ваши личные данные и не передает их третьим лицам;
переда**ё**т

2021-07-06 15:12 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* приложение для [Android](https://agrd.io/adguard_vpn_android), [iOS](https://agrd.io/ios_vpn), [Windows](https://agrd.io/windows_vpn_beta) и [Mac](https://agrd.io/mac_vpn_beta).
можно мобилки и десктопы в разные пункты разнести

2021-07-06 17:27 UTC, vbagirov requested changes

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Протоколы безопасности VPN – это инструменты, которые шифруют данные в VPN-туннеле и позволяют сохранить конфиденциальность пользователя в открытой сети. На данный момент существуют 7 основных VPN-пр
Я думаю тут можно оставить информацию про WireGuard, IPSec, OpenVPN (ну и разумеется AdGuard). Достаточно сказать что подавляющее большинство всех современных впнов используют один из этих трёх. Лучше на всякий случай конечно уточнить у кого-нибудь, что это действительно так. А про остальные можно одной строкой что есть и другие нр они либо малопопулярны, либо устарели и т.д.

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +7. [*Протокол AdGuard*](link). Одно из преимуществ нашего протокола в том, что его нельзя отличить от обычного браузинга. То есть VPN-туннель выглядит как обычный HTTPS-трафик, поэтому его чрезвычайн
Ты сравниваешь протокол (т.е. метод шифрования) с браузингом. Это не совсем корректно. Лучше сравнивать то, как выглядит твой трафик, передаваемый по протоколу AdGuard, с трафиком, который передаётся вообще не через впн.

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +## Что может скрыть VPN
Вот вместо этого раздела лучше раскрыть подробнее про кейсы применения VPN: 

1) анонимность - расскажи подробнее про то, чем может грозить потеря анонимности в сети.
2) секьюрность - аналогично, почему не стоит разбрасываться своими данными
3) обход геоблокировки - приведи кейсы, когда это полезно. Можно дать тут ссылку на будущую статью про стриминги и торренты

Можно использовать там куски текстов из этого раздела.

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +На скорость интернет-соединения при использовании VPN влияют несколько факторов: удалённость VPN-сервера от вашего настоящего местоположения, загруженность VPN-сервера, его пропускная способность, со
Ну самый главный фактор - что у тебя трафик идет не к веб-серверу и обратно, а по более длинному пути. Так что вот уже в самой схеме заложено, что скорость соединения снижается. А удаленность сервера это уже следствие.

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие VPN-провайдеры используют слабые протоколы, которые не позволяют VPN-соединению мимикрировать под обычный браузинг. Поэтому некоторые онлайн-сервисы могут обнаружить VPN-соединение и заблокиро
я бы не стал употреблять слово "слабые", просто типа обычные впн-протоколы сложно взломать, но легко отличить от обычного веб-трафика. Поэтому их легко заблокировать.

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +**Обрыв VPN-соединений**
Как-нибудь поаккуратней тут, чтоб себе в ногу не стрелять. Например, что есть факторы, которые могут привести к тому, что впн-соединения будет обрываться, особенно у не  самых надёжных провайдеров.

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +**Запрет VPN**
ну это можно внести в раздел про блокировку доступа, как-то упомянуть там просто

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* *собственный VPN-протокол*, который стабильно работает даже при слабом интернет-соединении и маскируется под обычный траффик, отчего его сложнее отследить и заблокировать;
тут ещё раз ссылку на наш протокол можно, ничего страшного

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* *политика «без логов»*, которая означает, что AdGuard VPN не собирает ваши личные данные и не передаёт их третьим лицам;
тут можно ссылку на политику конфиденциальности

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Наш VPN-сервис обладает несколькими важными преимуществами:
тут ссылку на будущую статью про преимущества

2021-07-06 17:27 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* браузерное расширение для [Chrome](https://agrd.io/vpn_chrome_extension), [Firefox](https://agrd.io/vpn_firefox_extension) и [Edge](https://agrd.io/vpn_edge_extension);
тут везде лучше ссылки на разделы кб про эти приложения/расширения, а не на скачивание прям

2021-07-07 13:31 UTC, vbagirov requested changes

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +При подключении к сети вашему компьютеру или мобильному устройству присваивается уникальный числовой идентификатор, или IP-адрес. Обычно, он состоит из чисел от 0 до 255, разделенных точками или двое
Наверное, неправильно прям уверенно говорить, что будет прям всегда всё записывать -- но определённо может, так и надо сказать. И "эта запись нужна" лучше заменить на "может быть использована".

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +VPN создаёт между вашим девайсом и VPN-сервером своеобразный туннель, в котором ваши данные зашифровываются и уже затем в защищённом виде попадают в открытый интернет. Поэтому вашему устройству будет
Мне кажется, всё ещё не совсем так. IP у твоего устройства остаётся прежний, но вот веб-сервер увидит в качестве IP-адреса отправителя только айпишник VPN-сервера, а не твой. Если есть сомнения, можно уточнить у кого-нибудь

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Протоколы безопасности VPN – это инструменты, которые шифруют данные в VPN-туннеле и позволяют сохранить конфиденциальность пользователя в открытой сети. На данный момент подавляющее большинство совр
`трех`
ё тут и везде по тексту проверь

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +2. *Open VPN*. Этот современный протокол имеет открытый исходный код, поэтому сторонние производители могут улучшать и обновлять технологию.
OpenVPN

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +3. *WireGuard*. Протокол работает ещё быстрее и стабильнее, чем OpenVPN и IPSec.
Я не уверен, что он прям быстрее и стабильнее. По крайней мере, погуглив, нашел только информацию, что у него есть как преимущества, так и недостатки относительно того же OpenVPN. Ты откуда брал инфу?

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Помимо этих VPN-протоколов есть и другие (например, TLS, SSTP, IKEv2), но они малопопулярны и не соответсвуют современным стандартам шифрования данных.
Правильнее будет "малопопулярны либо не соответствуют ...."

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +У нашего AdGuard VPN также есть собственный [*протокол*](link). Одно из его преимуществ состоит в том, что трафик, передаваемый с помощью протокола AdGuard, сложно отличить от обычного трафика. То ес
"нашего" тут явно лишнее

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +При подключении к ненадёжной или общедоступной сети данные на вашем устройстве могут стать уязвимыми для киберпреступников. Реквизиты банковских карт, логины и пароли, паспортные данные - все эти дан
длинное тире —

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие сайты, в том числе стриминговые сервисы и онлайн-платформы, доступны лишь в определённых странах. В частности, многие российские онлайн-кинотеатры доступны только на территории РФ, и, например
1) Что такое "онлайн-платформы"?
2) Давай уберем упоминание легальности/нелегальности на всякий случай. Оставь просто про то, что торренты недоступны в некоторых государствах.

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие VPN-провайдеры используют протоколы, которые не позволяют VPN-соединению мимикрировать под обычный трафик. Поэтому некоторые онлайн-сервисы могут обнаружить VPN-соединение и заблокировать испо
1) Тут не то что многие, а насколько я понимаю вообще все. Можешь уточнить у разработчиков в впн-чате.
2) Про легальность давай опять же уберем от греха подальше.

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Слабый сигнал, перегруженность сети, несовместимость VPN с брандмауэром, антивирусом и другими программами, устаревший VPN-протокол - всё это может стать причиной внезапного сбоя в VPN-соединении, ос
Длинное тире

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* [*политика «без логов»*](link), которая означает, что AdGuard VPN не собирает ваши личные данные и не передаёт их третьим лицам;
Здесь ссылка уже есть, можно найти на нашем сайте впна: adguard-vpn.com

2021-07-07 13:31 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +* браузерное расширение для [Chrome](link), [Firefox](link) и [Edge](link);
Про браузерное расширение будет одна статья, так что нет смысла в трех ссылках

2021-07-07 14:04 UTC, alim-shakirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие сайты, в том числе стриминговые сервисы и онлайн-платформы, доступны лишь в определённых странах. В частности, многие российские онлайн-кинотеатры доступны только на территории РФ, и, например
1) https://treewords.com/posts/92-chto-takoe-onlayn-platforma-i-zachem-ona-nuzhna-v-izuchenii-angliyskogo
или все равно не то?

2021-07-07 14:12 UTC, alim-shakirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие VPN-провайдеры используют протоколы, которые не позволяют VPN-соединению мимикрировать под обычный трафик. Поэтому некоторые онлайн-сервисы могут обнаружить VPN-соединение и заблокировать испо
1. тогда адгард впн тоже не может, хотя мы это прописываем дальше: собственный VPN-протокол, который стабильно работает даже при слабом интернет-соединении и маскируется под обычный трафик?

2021-07-07 15:05 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +При подключении к сети вашему компьютеру или мобильному устройству присваивается уникальный числовой идентификатор, или IP-адрес. Обычно, он состоит из чисел от 0 до 255, разделенных точками или двое
Эта запись может быть использован - несогласовано

2021-07-07 15:05 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +3. *WireGuard*. Его главные преимущества — простота использования, высокая производительности и низкая поверхность для атак.
высокая производительности - несогласовано

низкая поверхность для атак - я не понимаю, что тут имелось в виду

2021-07-07 15:05 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +Многие сайты, в том числе стриминговые сервисы и онлайн-платформы, доступны лишь в определённых странах. В частности, многие российские онлайн-кинотеатры доступны только на территории РФ, и, например
Ну бог с ним, пусть будут онлайн-платформы.

2021-07-07 15:09 UTC, vbagirov requested changes

2021-07-07 15:09 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.ru.md
> +**Обрыв VPN-соединений**
Лучше вообще предложение про недоступность в странах убрать. Оставить только про блокировку сервисами

2021-07-08 07:57 UTC, el-termikael approved these changes

2021-07-08 12:37 UTC, vbagirov requested changes

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +To understand how AdGuard VPN works, you should at first understand the general principles of the VPN service. A VPN is a Virtual Private Network that helps hide your location and protect your data o
Здесь тоже первое предложение вынести за заголовок.

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +2 .*Geoblocking bypassing*. Some sites are only available from certain countries and regions. Connecting to a VPN server that is located in one of these countries, you will be able to use previously
Тут пробел не туда попал

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +2 .*Geoblocking bypassing*. Some sites are only available from certain countries and regions. Connecting to a VPN server that is located in one of these countries, you will be able to use previously
И во втором предложении должно быть "By connecting ..."

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +When you connect to the network, your computer or mobile device is assigned a unique ID number, or IP address. It usually consists of numbers from 0 to 255, separated by dots or colons. Knowing this
Наверное либо "to a network", либо "to the Internet"

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +When you connect to the network, your computer or mobile device is assigned a unique ID number, or IP address. It usually consists of numbers from 0 to 255, separated by dots or colons. Knowing this
> Knowing this sequence, you can determine 

я думаю лучше "one can determine", а то полуается как будто ты сам свою локацию определяешь

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +A VPN creates a tunnel between your device and the VPN server, in which your data is encrypted and then gets into the open Internet in a secure form. Therefore, it will seem to the web server that yo
endpoint а не end point

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +3. *WireGuard*. Its main advantages are ease of use, high efficiency and low vulnerability to attacks.
на вайргард тоже можно дать ссылку на вики, да и на опенвпн в принципе тоже, почему нет

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Using an Internet connection, the user leaves his digital footprint, which can then be analyzed and used by third parties. For example, one of the online stores that you have visited can save your se
лучше писать their вместо his

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +If you connect to an unreliable or public network, the data on your device may become vulnerable to cybercriminals. Bank card details, usernames and passwords, passport data — all these data can be i
this data - нет мн.числа

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many sites, including streaming services and online platforms, are available only in certain countries. In particular, many Russian online movie theaters are available only on the territory of the Ru
вот про рашн муви тиатерс в английской статье точно не надо, приведи в пример нетфликс какой-нибудь или вообще без конкретики

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many sites, including streaming services and online platforms, are available only in certain countries. In particular, many Russian online movie theaters are available only on the territory of the Ru
Ещё я не уверен, что "on the network" - лучший вариант, когда говоришь не про конкретную сеть, а про интернет в целом. Мне кажется, лучше "on the web" или "on the Internet". Уточни этот вопрос.

2021-07-08 12:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many sites, including streaming services and online platforms, are available only in certain countries. In particular, many Russian online movie theaters are available only on the territory of the Ru
И вообще что значит "location that will be displayed"? Вроде нет какого-то места, где твоя локация прям выставлена на всеобщее обозрение. Скорее просто видимый айпишник ассоциируется с определённой локацией.

2021-07-08 12:57 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +2 .*Geoblocking bypassing*. Some sites are only available from certain countries and regions. Connecting to a VPN server that is located in one of these countries, you will be able to use previously
Geoblocking bypassing —> Bypassing geoblocking

2021-07-08 13:14 UTC, el-termikael requested changes

2021-07-08 13:14 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +A VPN creates a tunnel between your device and the VPN server, in which your data is encrypted and then gets into the open Internet in a secure form. Therefore, it will seem to the web server that yo
A VPN creates a tunnel between your device and the VPN server. Your data goes through this tunnel, gets encrypted and then enters the open Internet in a secure form.

2021-07-08 13:14 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Using an Internet connection, the user leaves his digital footprint, which can then be analyzed and used by third parties. For example, one of the online stores that you have visited can save your se
Internet service providers —> ISPs

2021-07-08 13:14 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +3. **Geoblocking bypassing**
лучше Bypassing geoblocking

2021-07-08 13:14 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many VPN providers use protocols that do not allow the VPN connection to imitate normal traffic. Therefore, some online services may detect a VPN connection and block users who utilize it.
nd block users who utilize it — или лучше ban

2021-07-08 13:14 UTC, el-termikael commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +* [*"No logs" policy*](https://adguard-vpn.com/en/privacy.html), which means that AdGuard VPN does not collect your personal data and does not transfer it to third parties
No-logs policy

2021-07-08 13:37 UTC, vbagirov requested changes

2021-07-08 13:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many sites, including streaming services and online platforms, are available only in certain countries. In particular, some online movie theaters are available only on the specific territories, and,
1) online movie theaters - наверное, streaming services более широкое и популярное понятие

2021-07-08 13:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many sites, including streaming services and online platforms, are available only in certain countries. In particular, some online movie theaters are available only on the specific territories, and,
>With a VPN, you can change your visible IP address (and the location that can be defined on the web) and use previously blocked resources.

With a VPN, you can change your visible IP address (and thus your perceived location) and use previously blocked resources.

2021-07-08 13:37 UTC, vbagirov commented on 11.vpn/010.adguard-vpn-general/010.how-vpn-works/docs.en.md
> +Many VPN providers use protocols that do not allow the VPN connection to imitate normal traffic. Therefore, some online services may detect a VPN connection and block users who utilize it.
Ban тоже не то. Если уж и менять, то на что-то вроде "and restrict access for users with VPNs"

2021-07-08 13:47 UTC, vbagirov approved these changes

2021-07-08 14:25 UTC, vbagirov approved these changes

2021-07-08 14:26 UTC, merged