agm 958 vpn for ios install-deinstall
AdguardTeam/AdguardKnowledgeBase pull request #894
Opened 2021-07-08 15:41 UTC by alim-shakirov

2021-07-08 15:46 UTC, el-termikael requested changes

2021-07-08 15:46 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Вы можете установить AdGuard VPN на свой iPhone или iPad, если на вашем устройстве установлен **iOS 11.2 или более поздней версии**.
установленА (если OS — операционка) или установлено (если ПО)

2021-07-08 15:46 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Скачать и установить приложение *AdGuard для iOS* можно бесплатно в каталоге *App Store*. Для этого вы можете просто перейти по [этой ссылке](https://agrd.io/ios_vpn) и нажать на значок загрузки или
в каталоге лишнее
вы можете просто перейти по... и нажать —> просто перейдите... и нажмите... или выполните

2021-07-08 15:46 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +3. Выберите *AdGuard VPN — Unlimited & Fast* в списке появившихся приложений и затем нажмите на *Загрузить*. При необходимости введите в открывшемся окне ваш пароль от учётной записи Apple ID.
затем нажмите на *Загрузить* —> нажмите *Загрузить*.

2021-07-08 15:46 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +4. Подождите, пока закончится процесс загрузки, и нажмите *Открыть*.
Дождитесь окончания загрузки

2021-07-08 15:46 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Если вы решили удалить приложение AdGuard VPN для iOS, найдите иконку этого приложения на экране "Домой" и удерживайте её. В открывшемся списке нажмите на *Удалить приложение*.
лучше кавычки-ёлочки: «»

2021-07-08 15:53 UTC, vbagirov requested changes

2021-07-08 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Узнать больше о приложении AdGuard VPN для iOS вы можете в [этой статье](link).
Ну тут ты как раз уже знаешь, какой будет урл.

2021-07-08 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Вы можете установить AdGuard VPN на свой iPhone или iPad, если на вашем устройстве установлен **iOS 11.2 или более поздней версии**.
ещё надо спросить у разработчиков про iPad OS

2021-07-08 16:11 UTC, alim-shakirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Вы можете установить AdGuard VPN на свой iPhone или iPad, если на вашем устройстве установлен **iOS 11.2 или более поздней версии**.
сказали, что без разницы: и на айфоне, и на айпаде iOS 11.2 и выше

2021-07-08 16:17 UTC, el-termikael approved these changes

2021-07-08 16:27 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Вы можете установить AdGuard VPN на свой iPhone или iPad, если на вашем устройстве установлен **iOS 11.2 или более поздней версии**.
Просто iPad OS позиционироуетс Apple как самостоятельная ОС, мне кажется логично написать, что на них тоже работает (начиная с 13.1 или когда там они ответвились, и все после неё)

2021-07-08 16:59 UTC, vbagirov requested changes

2021-07-08 16:59 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +* [Удаление AdGuard VPN для iOS](#deinstallation)
deinsatllation как-то не особо говорят про софт. Давай поменяем анкоры на `#install` и `#uninstall`

2021-07-08 16:59 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Вы можете установить AdGuard VPN на свой iPhone или iPad, если на вашем устройстве установлена **iOS 11.2 или более поздней версии**.
Просто iPad OS позиционироуется Apple как самостоятельная ОС, мне кажется логично написать, что на них тоже работает (начиная с 13.1 или когда там они ответвились, и все после неё)

2021-07-08 16:59 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.ru.md
> +Скачать и установить приложение *AdGuard для iOS* можно бесплатно в каталоге *App Store*. Для этого вы просто перейдите по [этой ссылке](https://agrd.io/ios_vpn) и нажмите на значок загрузки или выпо
Тут второе предложение не по-русски как-то. Посмотри, там Лена оставляла комменты про него

2021-07-09 12:00 UTC, el-termikael requested changes

2021-07-09 12:00 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.en.md
> +3. Select *AdGuard VPN - Unlimited & Fast* from the list of suggested applications, and then click *Download*. If necessary, enter your Apple ID account password in the opened window.
, and then click *Download* —>  and tap *Download*

2021-07-09 13:50 UTC, el-termikael approved these changes

2021-07-09 14:12 UTC, vbagirov requested changes

2021-07-09 14:12 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.en.md
> +If you decided to delete the AdGuard VPN for iOS, find the icon of this app on the Home Screen and hold it. In the opened list, tap *Remove App*.
the AdGuard VPN for iOS -- артикль не нужен

2021-07-09 14:21 UTC, el-termikael commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.en.md
> +* [AdGuard VPN for iOS uninstallation](#uninstall)
я нашла на мультитране и реверсо
не самые показательные ресурсы, но

2021-07-09 15:34 UTC, alim-shakirov commented on 11.vpn/030.adguard-vpn-for-ios/02.Installation/docs.en.md
> +* [AdGuard VPN for iOS uninstallation](#uninstall)
на wiktionary тоже есть

2021-07-09 15:40 UTC, vbagirov approved these changes

2021-07-09 15:43 UTC, merged