920-android-overview
AdguardTeam/AdguardKnowledgeBase pull request #895
Opened 2021-07-09 15:23 UTC by el-termikael

updated Android overview for Kb

2021-07-27 15:53 UTC, vbagirov requested changes

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +## Privacy protection
Странно, что этот раздел внутри ад блокинга, когда у нас есть стелс мод (про который как будто бы не упомянуто нигде)

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +We keep emphasising the importance of not being tracked because tracking is indeed the new cyber plague, and we certainly don't appreciate users' data being used [this](https://adguard.com/en/blog/ac
Что-то многовато ссылок на довольно узконаправленные блогостатьи на мой вкус. Вот это предложение вообще непонятно какое отношение имеет к базе знаний.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +AdGuard Tracking Protection filter protects your personal data from automatic data gathering systems. We strongly recommend having this or similar filter on if you care about your online privacy. The
DNSCrypt это довольно устаревший протокол, скорее ты имела в виду DNS privacy в целом.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +All the icons you will see on the screen are clickable, and by tapping on them you will open a screen showing app-specific traffic to help you make more informed decisions. As can be seen, AdGuard is
Что-то мне заход с `in departments` прям совсем не нравится, может перефразировать?

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +> Tip: use the Import feature to upload your favorite filter to the User rules. But be careful, it will overwrite any rules that are currently added there.
если импортируешь уже готовый любимый фильтр, лучше импортировать его через кастомные фильтры. Импорт юзер рулз скорее для переноса между девайсами и т.д.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +[DNS filtering](https://kb.adguard.com/en/general/dns-filtering-android) is one of the most effective ways to protect your device from ads and phishing.
лучше начать с того что у днс фильтрации есть как свои большие плюсы, так и большие минусы.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +A bit of a theory refresher: DNS stands for 'Domain name system', and its purpose is to translate domain names into something browsers can understand, i.e. IP addresses. So, each time you go to a web
Напрашивается ссылка сюда: https://kb.adguard.com/en/general/dns-filtering#what-is-dns

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +A bit of a theory refresher: DNS stands for 'Domain name system', and its purpose is to translate domain names into something browsers can understand, i.e. IP addresses. So, each time you go to a web
bad requests - в кавычках, а лучше раскрыть, что конкретно имеется в виду под плохими запросами

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +A bit of a theory refresher: DNS stands for 'Domain name system', and its purpose is to translate domain names into something browsers can understand, i.e. IP addresses. So, each time you go to a web
Ну и можно добавить фразу в конце, что таким образом ответ не будет получен и запрос по сути заблокируется на корню

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +DNS filtering has its own separate tab within the AdGuard for Android app home screen. Here you can choose which type of DNS you wish to use (it can be either regular DNS or high security DNS, also k
про DNSCrypt опять, не надо. Ну и тире длинное поставить

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +What needs to be taken into account is that DNS blocking is more of an additional feature, which has several nuances. Most of them are mentioned above in the Knowledge Base article.
Ну это уже давно одна из самыз популярных опций Адгарда, так что лучше сказать что DNS - это просто независимая штука, которая дополняет protection suit.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +How exactly does AdGuard block DNS requests? It has a special DNS filter which contains a large list of ad and tracker domains, which it uses in conjunction with User rules to recognize 'bad' request
Здесь как-то не слишком чётко структурировано. Надо объяснить, что есть DNS-серверы, которые могут что-то блокировать сами - тут уж в зависимости от того, какой сервак юзер выбрал, а есть именно встроенная в AdGuard DNS-фильтрация, которая фильтрует DNS-запросы "поверх" того, что делает сервер, уже на самом устройстве.

Если нужна помощь с тем, чтобы разобраться - обращайся.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +The simplicity of this approach is both a benefit and a disavantage. The main advantage of this approach is that it's both battery life friendly and traffic-saving. Once a domain is blocked, it won't
Надо наверное уточнить, что иногда заблокировать рекламу по DNS можно только при помощи правила, которое при этом параллельно что-то сломает. В таком случае мы просто это правило не добавляем, и реклама останется незаблокированной - потому что альтернатива "сайт вообще не работает" ещё хуже

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +The simplicity of this approach is both a benefit and a disavantage. The main advantage of this approach is that it's both battery life friendly and traffic-saving. Once a domain is blocked, it won't
Ну и тут где-то в этом подразделе надо снова ссылку на https://kb.adguard.com/en/general/dns-filtering, только на другой анкор уже

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +But AdGuard for Android "DNS package" does not end just there. One of the useful perks is an option to select *absolutely any* DNS server to use. At your service is a list consisting of dozens of ser
Если ты тут говоришь про дефолтный список серверов тоже, то странно что в заголовке "custom". Я предлагаю либо подзаголовок поменять, либо затронуть тему дефолтного списка серверов раньше, а тут уже про кастомные рассказать

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +There are several asons to use a custom DNS server instead of one offered by your ISP by default. Some servers are faster, some provide ad blocking or parental control solutions, some enhance your pr
1) several asons
2) https://kb.adguard.com/en/general/dns-providers - надо сюда ссылку где то, типа вот тут ещё больше серваков если вам мало, плюс можно в один тап прям добавить в адгард из той статьи любой сервак

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +This option is available on the *Settings > DNS Filtering > DNS Requests blocking* screen.
тут ссылку на https://filterlists.com/

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +This option is available on the *Settings > DNS Filtering > DNS Requests blocking* screen.
ну не конкретно в этом предложении, а в этом подразделе

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +### DNSCrypt
Тут надо много менять, я не думаю, что каждый тип протокола надо отдельно расписывать (а есть ещё DNS-over-HTTPS и DNS-over-TLS). Лучше где-то раньше, где речь про серверы, рассказать, что они могут также отличаться поддерживаемыми типами протоколов, какие типы протоколов бывают, почему важно защищать DNS-трафик и т.д. И тогда нужда в этом и следующем разделах пропадет.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +### DNSCrypt
Разве что можно будет сделать небольшой подраздел 3го уровня про DNS-over-QUIC, порекламировать там немного AdGuard DNS со ссылочками всякими.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +A proxy server is basically another computer serving as a hub that processes your internet requests. You can set up AdGuard to route all your device's traffic through any proxy — and you'll be able t
look it u

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +# Other features
Сюда надо ещё подраздел про лицензию, что она даёт в сравнении с бесплатной версией, как активировать и т.д.

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +There are too many features to describe them all in detail, so let me simply list them here:
в той структуре, что у тебя сейчас, эти фичурз как будто относятся к extensions support, а это совсем не так

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +* By tapping on a little battery icon on the main screen of the app you will get to the "Battery Usage" screen. System battery stats [are often wrong](https://kb.adguard.com/ут/android/solving-proble
ссылка кривая

2021-07-27 15:53 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +If you'd like to disable Compatibility Mode for any reason, it's very simple to do so from AdGuard ad blocker settings, just toggle the switch. Additionally, you can add AdGuard ad blocker and AdGuar
пробел лишний после will

2021-07-27 16:48 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +AdGuard for Android, on the contrary, is a paid full-fledged app and one of our flagship products. It has an extensive list of features both in ad blocking and in privacy protection areas. And now we
<img width="770" alt="Снимок экрана 2021-07-27 в 19 48 03" src="https://user-images.githubusercontent.com/58733007/127194894-9e66422f-4f1a-4cd2-b523-2c348b8fe191.png">
а не много ли блок квоутс?

2021-07-27 16:53 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +But most of popular ad blockers are browser extensions, and those apps that are present on the Android market, sadly, are not stellar in their abilities. For example, here's a link to a [comparative
тогда убираю этот абзац?

2021-07-27 16:57 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +## Privacy protection
да, про стелс мод пока не написала(

2021-07-29 11:02 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +How exactly does AdGuard block DNS requests? It has a special DNS filter which contains a large list of ad and tracker domains, which it uses in conjunction with User rules to recognize 'bad' request
нужна, да
пока только так(
There are two methods of DNS blocking:
1) some DNS servers can block DNS requests to potentially harmful domains;
2) there is built-in DNS filtering that blocks DNS requests in addition to what the DNS server does on the device.

2021-07-30 14:49 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +> Tip: use the Import feature to upload your favorite filter to the User rules. But be careful, it will overwrite any rules that are currently added there.
сейчас нет раздела про custom filters, добавить его?

2021-07-30 14:50 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +There are too many features to describe them all in detail, so let me simply list them here:
тогда вынести Extensions support перед Other features?

2021-08-04 18:06 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +### DNS-over-QUIC
Всё хорошо, но надо перенести этот кусочек подразделом в раздел DNS servers, где ты говорила про разные протоколы

2021-08-04 18:07 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +* Stealth mode
в других местах было с большой - Stealth Mode

2021-08-04 18:08 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +# License
Логично поставить этот раздел в самый конец, перед Other features

2021-08-04 18:08 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +* By tapping a little battery icon on the main screen of the app you will get to the "Battery Usage" screen. System battery stats [are often wrong](https://kb.adguard.com/ут/android/solving-problems/
всё ещё кривая ссылка

2021-08-06 08:27 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +> AdGuard for Android, on the contrary, is a full-fledged app and one of our flagship products. It has an extensive list of features both in ad blocking and in privacy protection areas, using part of
это точно выкидываю?
There is often confusion when it comes to installing AdGuard for Android: people want to try out this mobile app for Android, look for it on Google Play, find AdGuard Content Blocker instead, download it and can't understand why it has so little to offer.

2021-08-06 08:59 UTC, el-termikael commented on 04.android/01.overview/docs.en.md
> +Nowadays most websites work via HTTPS, the web protocol where the last S letter stands for "secure". It happened so that advertisers use it as well, this is why [HTTPS filtering](https://kb.adguard.c
почему? «Так сложилось, что рекламщики тоже его используют»

2021-08-06 11:00 UTC, vbagirov requested changes

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +AdGuard Content Blocker is an app available in Google Play that has truncated functionality to meet restrictions imposed by the store. AdGuard for Android, on the other hand, is a powerful applicatio
Я имел в виду объединить с дисклеймером внутри блок квоута, ну и может добавить в эту фразу что-то про то, что АГ для Андроид скачивается с сайта, и ссылку зашить туда на https://adguard.com/en/adguard-android/overview.html

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +All the icons you will see on the screen are clickable, and by tapping on them you will open a screen showing app-specific traffic to help you make more informed decisions. As can be seen, AdGuard is
with the ad filtering - the нужно?

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +The DNS Filtering module allows to configure DNS settings of a user's device, including the chosen DNS server, DNS protocol, and DNS filters that block ads and trackers.
of a user's device? Наверное можно как-то лучше сказать, особенно учитывая, что речь про конкретный девайс, на котором установлен Адгард

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +A bit of a theory refresher: [DNS](https://kb.adguard.com/en/general/dns-filtering#what-is-dns) stands for "Domain name system", and its purpose is to translate domain names into something browsers c
не очень хорошо, ссылка вокруг трёх букв всего, не очень читается

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +2) there is built-in DNS filtering that blocks DNS requests in addition to what the DNS server does.
Ну ты просто убрала, что DNS фильтрация работает на устройстве, а надо было поменять фразу так, чтобы не было двоетолков. Может так?

built-in DNS filtering that works right on your device and can block DNS requests, in addition to what's blocked by the selected DNS server.

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +While some ot the features in AdGuard for Android are free, others require [purchasing a license](https://adguard.com/en/license.html). There are Personal (up to three devices) and Family (up to 9 de
Везде отступ после заголовка, а тут нет

2021-08-06 11:00 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +# Other features
Тоже нет отступа

2021-08-09 14:58 UTC, vbagirov requested changes

2021-08-09 14:58 UTC, vbagirov commented on 04.android/01.overview/docs.en.md
> +> Disclaimer: AdGuard for Android is not to be confused with AdGuard Content Blocker. AdGuard Content Blocker is an app [available in Google Play](https://play.google.com/store/apps/details?id=com.ad
А ссылку то зачем на гуглплей? Нам не особо интересно ,чтобы юзер пошел скачивать контент блокер. Можно дать на раздел в кб максимум

2021-08-18 10:50 UTC, Dariamag requested changes

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<a id=" filtering-log"></a>
<a id="filtering-log"></a>

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<a id="user-filters"></a>
<a id="user-filter"></a>

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Главная цель блокировщика рекламы – это, собственно, блокировка рекламы, поэтому неудивительно, что у большинства приложений алгоритмы блокировки практически не отличаюются. Механизм фильтрации рекла
отличаюются —》 отличаются

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Большинство мобильных блокировщиков рекламы для Android работают по тому же принципу, но  is only one of the many features for AdGuard. Read [this comparative article](https://adguard.com/en/blog/adg
тут англ

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/android-features/how-https-works.jpg?1" style="border: 1px solid #efefef; padding: 2px;" />
https://cdn.adguard.com/public/Adguard/Blog/android-features/how-https-works-ru.jpg

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Многие сайты собирают данные о своих посетителях, такую как IP-адреса, информацию о браузере и операционной системе, разрешение экрана и даже страницу, с которой пользователь перешёл на сайт. На неко
, такую —〉 , такие

посещеании —〉 посещении

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/Android/3-6/privacy-protection.png" style="border: 0px solid #efefef; max-width: 300px; padding: 2px;" />
https://cdn.adguard.com/public/Adguard/Blog/Android/3-6/stealth-mode.png

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/Android/3-6/privacy-protection.png" style="border: 0px solid #efefef; max-width: 300px; padding: 2px;" />
в англ версии тоже надо проверить

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +В то же время, хотим обратить ваше внимание на то, что ваша личная информация никуда *не* передаётся, и даже AdGuard *не* знает, какие сайты вы посещаете. Для проверки безопасности используются не от
с обновлением базу данных —》с обновлением базы данных

антифинг —》 антифишинг

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/Android/3-6/privacy-protection.png" style="border: 0px solid #efefef; max-width: 300px; padding: 2px;" />
хотя я так понимаю, что они будут переделываться - в таком случае пофиг

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/Android/3-6/log-details_ru.png" style="border: 0px solid #efefef; max-width: 300px; padding: 2px;" />
тоже картинка не работает

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Кстати, всякий раз, когда вы используете Журнал фильтрации для блокировки каких-либо запросов, в Пользовательском фильтре появляется соответствующее правило. Для отмены блокировки запросы достаточно
Для отмены блокировки запросы -?

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +DNS-блокировка – это независимая функция, которая дополняет AdGuard .
лишний пробел перед точкой

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Он привносит всё хорошее, что QUIC has to offer — готовое шифрованиеn, ускоренное время подключени connection times, better performance when data packets are lost. Also, QUIC is supposed to be a tran
тут много английского затесалось

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Пользовательские скрипты (мы также называем их расширениями) - это, по своей сути, мини-программы, написанные на Javascript и меняющие поведение одного или многих веб-сайтов. Обычно вам потребовался
Обычно вам потребовался бы специальный менеджер скриптов, чтобы использовать их, и вообще всё это обычно

(обычно, обычно)

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Лучший вид совместимости — это когда вы устанавливаете два приложения и они просто начинают работать вместе. Presuming you уже установлен блокировщик рекламы AdGuard, просто скачайте AdGuard VPN из P
Presuming you уже установлен - ?

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +If you'd like to disable Compatibility Mode for any reason, it's very simple to do so from AdGuard ad blocker settings, just toggle the switch. Additionally, you can add AdGuard ad blocker and AdGuar
english again

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Если по какой-то причине вы захотите отключить режим совместимости, это просто сделать в настройках блокировщика рекламы AdGuard, просто переключите переключатель. Кроме того, вы можете добавить плит
переключите переключатель - не оч

2021-08-18 10:50 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +В то время как некоторые функции AdGuard для Android бесплатны, для использования других нужно [приобрести лицензию](https://adguard.com/ru/license.html). Есть Персональные (до трёх устройств) и Семе
очень английская фраза. —》
Некоторые функции AdGuard для Android бесплатны, а для использования других нужно [приобрести лицензию](https://adguard.com/ru/license.html).

доступны offers следующие функции —- и снова англ слово

2021-08-23 15:40 UTC, vbagirov requested changes

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Фишинг – это вид интернет-мошенничества, нацеленный на получение доступа к ценной информации вроде логинов, паролей, платёжных данных и т.д. Такой обман чаще всего осуществляется с помощью фальшивых
и вроде убытки не наносят, а терпят

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Все иконки, которые вы видите на экране, кликабельны, нажав на них, вы увидите окошко. В нём будет показана статистика трафика приложения, что поможет вам принимать решения относительно разрешений пр
кликабельны - легальное слово?

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Все иконки, которые вы видите на экране, кликабельны, нажав на них, вы увидите окошко. В нём будет показана статистика трафика приложения, что поможет вам принимать решения относительно разрешений пр
особенно применительно к андроиду

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Как упоминалось выше, AdGuard для Android использует набор фильтров для блокировки рекламы. Однако в настройках приложении можно найти и так называемые *Пользовательские правила*, которые позволяют с
в настройках приложении -> приложения

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +> Подсказка: используйте функцию «Импорт», чтобы загрузить свой любимый фильтр в качестве пользовательского.
Для этого есть раздел "custom filters", вроде. Ну либо перефразировать надо, а то "любимый фильтр" звучит как "любимый фильм", т.е. что-то извне, а тогда действительно кастом фильтерс лучше подойдёт

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +У [DNS-фильтрации](https://kb.adguard.com/en/general/dns-filtering#what-is-dns) есть отдельная вкладка в меню приложения AdGuard для Android. Здесь вы можете выбрать, какой тип DNS хотите использоват
ссылка на англ ведёт

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +[Но как именно работает DNS-фильтрация](https://kb.adguard.com/ru/general/dns-filtering#how-does-dns-filtering-work)? Есть специальный DNS-фильтр, который содержит большой список рекламных и отслежив
Мне кажется, лучше не начинать предложение с гиперссылки, давай "Но" вынесем из-под ссылки

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Но «пакет DNS-функций» приложения AdGuard для Android на этом не заканчивается. Один из полезных бонусов — возможность выбрать *абсолютно любой* DNS-сервер. В вашем распоряжении список из десятков се
нельзя говорить, что это полный список

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +DNS-серверы различаются не только по функциям, но и по поддерживаемым протоколам. Существует три основных типа протоколов, по которым работают DNS-серверы: HTTPS, TLS и QUIC. Соответственно, существу
я бы не стал использовать выражение "самый выдающийся". Лучше что-то типа "обладает наибольшими преимуществами"

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +DNS-over-QUIC (DoQ) — это относительно новый протокол шифрования, а AdGuard DNS — первый публичный резолвер, который использует новый протокол QUIC. В отличие от DoH and DoT, DoQ использует QUIC в ка
DoH and DoT

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +* Перейдите в *Настройки* > и включите DNS-фильтрацию в одноимённом разделе
лишняя `>`

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Вы найдёте его в разделе *Настройки > DNS фильтрация > Фильтры DNS*. Он поддерживает два типа синтаксиса: урезанный синтаксис AdGuard и hosts-синтаксис. Познакомиться с ними ближе вы можете в нашей [
Давай сделаем не "урезанный синтакисис AdGuard", а "синтаксис AdGuard (в урезанной форме)", а то подумают что-нб не то

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Пользователи AdGuard теперь могут добавлять [собственные DNS-фильтры](https://filterlists.com/) или hosts-списки по URL. Это весьма полезная опция, учитывая, как популярны списки hosts среди интернет
Что значит "теперь"? КБ вроде как описывает текущее состояние, а не изменения в какой-то версии

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Пользовательские скрипты (мы также называем их расширениями) - это, по своей сути, мини-программы, написанные на Javascript и меняющие поведение одного или многих веб-сайтов. Обычно вам потребовался
Я конечно против эмоциональных восклицаний в КБ, но если очень сильно хочется, то не буду мешать

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Пользовательские скрипты (мы также называем их расширениями) - это, по своей сути, мини-программы, написанные на Javascript и меняющие поведение одного или многих веб-сайтов. Обычно вам потребовался
а вот тире там кажется короткое. Ну и вообще прогони поиск по тексту на момент коротких тире

2021-08-23 15:40 UTC, vbagirov commented on 04.android/01.overview/docs.ru.md
> +Приложения распознают друг друга и сделают всё, что нужно для бесперебойной совместной работы. А вам останется только наслаждаться интернетом без рекламы и всеми преимуществами VPN. Кстати, так же хо
там точно нет ограничений типа исключений приложений в впн-приложении?

2021-08-23 16:10 UTC, el-termikael commented on 04.android/01.overview/docs.ru.md
> +Фишинг – это вид интернет-мошенничества, нацеленный на получение доступа к ценной информации вроде логинов, паролей, платёжных данных и т.д. Такой обман чаще всего осуществляется с помощью фальшивых
кто-то наносит, а кто-то терпит))
https://fish.gov.ru/news/2016/03/04/krasnyj-priliv-nanosit-ubytki-lososevodam-chili/

2021-08-23 16:11 UTC, el-termikael commented on 04.android/01.overview/docs.ru.md
> +Все иконки, которые вы видите на экране, кликабельны, нажав на них, вы увидите окошко. В нём будет показана статистика трафика приложения, что поможет вам принимать решения относительно разрешений пр
да, вполне, часто его встречала
к андроиду нет, если придраться

2021-08-24 14:54 UTC, vbagirov approved these changes

2021-08-30 12:20 UTC, vbagirov submitted a review, later dismissed

2021-08-30 13:02 UTC, Dariamag commented on 04.android/01.overview/docs.en.md
> +> Disclaimer: AdGuard for Android is not to be confused with AdGuard Content Blocker. AdGuard Content Blocker is an app [available in Google Play] that has truncated functionality to meet restriction
ссылка на контент блокер? https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker

2021-08-30 13:03 UTC, Dariamag commented on 04.android/01.overview/docs.en.md
> +> Tip: use the Import feature to tranfser your rules to a different device.
tranfser -> transfer

2021-08-30 13:15 UTC, Dariamag commented on 04.android/01.overview/docs.ru.md
> +Большинство мобильных блокировщиков рекламы для Android работают по тому же принципу, но возможности AdGuard куда шире. Прочитайте эту сравнительную статью](https://adguard.com/ru/blog/adguard-vs-ada
тут ссылка не работает, лишний слеш

2021-08-30 13:27 UTC, Dariamag approved these changes

2021-08-30 13:27 UTC, merged