[agm 968] vpn iOS solving problems logs
AdguardTeam/AdguardKnowledgeBase pull request #898
Opened 2021-07-12 16:20 UTC by alim-shakirov

2021-07-13 10:57 UTC, vbagirov requested changes

2021-07-13 10:57 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/docs.en.md
> +---
Здесь нужен какой-то текст и ссылки на соотв статьи. Посмотри, как сделан аналогичный раздел в AdGuard для Android.

2021-07-13 10:57 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +Иногда служба поддержки AdGuard VPN может попросить вас отправить нам логи отдельно. Для этого воспользуйтесь функцией "Экспортировать логи" в пункте "Поддержка".
Не хватает инструкции о том, как собрать детальные логи. Можно сделать отдельным пунктом через `## Debug logs` или как там они называется, сделать анкор и мини-table of contents в начале.

2021-07-13 10:57 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +4. Напротив пункта "Отправить детальную информацию" по умолчанию стоит галочка, а это значит, что отправляя отчет, вы также отправляете логи.
Логи кстати за какое время отправляются? За всё время начиная с установки приложения, или у них есть срок жизни?

2021-07-13 11:09 UTC, alim-shakirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +4. Напротив пункта "Отправить детальную информацию" по умолчанию стоит галочка, а это значит, что отправляя отчет, вы также отправляете логи.
мне сказали, что у они пишутся непрерывно, но у них есть лимит вроде бы на 15 строк

2021-07-13 11:09 UTC, alim-shakirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +3. В открывшейся форме введите свой Email-адрес для обратной связи и опишите найденную ошибку, включив туда время, когда эта ошибка произошла. Если не помните точное время, то напишите приблизительно
Илья написал, что это не нужно делать
необходимо только написать время ошибки, хотя бы приблизительное

2021-07-13 17:04 UTC, vbagirov requested changes

2021-07-13 17:04 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +5. Переключите уровень логирования снова на "Стандартный".
И "переключите уровень логирования снова" звучит не по-русски. Гораздо лучше "Переключите уровень логирования обратно"

2021-07-13 17:04 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +>Если вам по какой-либо причине удобнее отправить нам логи другим способом, вы можете экспортировать их самостоятельно. Для этого выберите "Экспортировать логи" в разделе "Поддержка".
Ещё я подумал, что эту фразу можно также добавить в конец параграфа про обычные логи, иначе тот, кто пришел целенаправленно за инструкцией про обычные логи, может здесь её просто не заметить.

2021-07-13 17:04 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/030.integrated-mode/docs.ru.md
> +В приложении AdGuard VPN по умолчанию включен Основной режим работы, при котором используется собственный [протокол AdGuard VPN](link). Он обеспечивает лучшую комбинацию скорости и безопасности соеди
"Блокировщик не работает на IPSec протоколе, потому что IPSec -- это VPN-протокол. Ну либо я неправ, но тогда уточни ещё раз, что это точно корректная фраза, и поправь меня."

Этот комментарий ты не заметил или уточнил, и тут всё корректно?

2021-07-13 17:20 UTC, alim-shakirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/030.integrated-mode/docs.ru.md
> +В приложении AdGuard VPN по умолчанию включен Основной режим работы, при котором используется собственный [протокол AdGuard VPN](link). Он обеспечивает лучшую комбинацию скорости и безопасности соеди
я исправил на "использует IPSec-протокол"

2021-07-13 17:23 UTC, alim-shakirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +4. Если возможно, воспроизведите действия, которые привели к ошибке.
там логируется только само приложение, остальные не трогает

2021-07-13 18:03 UTC, vbagirov requested changes

2021-07-14 09:17 UTC, vbagirov requested changes

2021-07-14 09:17 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.ru.md
> +2. Если у вас уже есть личный кабинет AdGuard, вы можете оформить подписку через него также на [нашем сайте](https://my.adguard.com/ru/main.html). Зайдите в свой аккаунт и выберите "Мои лицензии" в м
Два вторых пункта.

2021-07-14 09:17 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.ru.md
> +2. Если у вас уже есть личный кабинет AdGuard, вы можете оформить подписку через него также на [нашем сайте](https://my.adguard.com/ru/main.html). Зайдите в свой аккаунт и выберите "Мои лицензии" в м
"вы можете оформить подписку через него также на нашем сайте" - я понимаю, что ты имел в виду, но звучит тяжело для понимания, надо перефразировать. Плюс про "my.adguard.com" лучше писать "в личном кабинете AdGuard", а не "на нашем сайте", потому что всё-таки это вспомогательный домен.

2021-07-15 15:53 UTC, vbagirov requested changes

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.en.md
> +AdGuard VPN is available in two versions — free and unlimited. The subscription allows you to use the app on maximum: without restrictions on traffic, connection speed and the choice of locations. Yo
Почти уверен, что `on maximum` не говорят

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.en.md
> +1. The first option is through an in-app purchase in the app itself. To do this, go to AdGuard VPN and click on the arrow in the upper-right corner of the screen. There are two types of subscriptions
У нас на сайте `yearly subscription`, лучше по возможности придерживаться этой формулировки, а не annual. Это несколько раз в пре встречается.

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.en.md
> +1. The first option is through an in-app purchase in the app itself. To do this, go to AdGuard VPN and click on the arrow in the upper-right corner of the screen. There are two types of subscriptions
>Select the highest priority for you

Я не понял эту фразу вообще. Видимо, лучше перефразировать.

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.en.md
> +3. You can also subscribe via [AdGuard personal account](https://my.adguard.com/ru/main.html), if you have one. Log in to your account and select "My Licenses" from the menu on the left. Click "Buy A
`ru` убрать из ссылки

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.en.md
> +1. Open AdGuard VPN for iOS and, if possible, replay the actions that led to the error. Remember the exact time when this error occurred.
replay? Repeat наверное лучше, или reproduce. Это несколько раз по тексту встречается

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.en.md
> +3. In the opened form, enter your Email address for feedback and describe the error found, including the time when this error occurred. If you can't reproduce the problem, specify as accurately as po
ранее было `email`, теперь `Email` - как правильно?

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.en.md
> +4. Replay the actions that led to the error, and remember the time when it occurred.
вместо remember лучше "note" или "take notice of"

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/030.integrated-mode/docs.en.md
> +AdGuard VPN has the General operating mode enabled by default, which uses its own [AdGuard VPN protocol](link). It provides the best combination of connection speed and security. However, this operat
the AdGuard VPN, the AdGuard ad blocker - не нужны артикли, это имена собственные

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/docs.en.md
> +* [How to collect and send logs](https://kb.adguard.com/ru/vpn/adguard-vpn-for-ios/solving-problems/logs)
здесь и в следующей строке у тебя `ru`

2021-07-15 15:53 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/docs.en.md
> +* [How to combine AdGuard VPN and AdGuard ad blocker](https://kb.adguard.com/en/vpn/adguard-vpn-for-ios/solving-problems/subscription)
Здесь заголовок от другой статьи, должно быть про подписку

2021-07-16 10:54 UTC, vbagirov requested changes

2021-07-16 10:54 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/010.subscription/docs.en.md
> +AdGuard VPN is available in two versions — free and unlimited. The subscription allows you to use all options of the app: without restrictions on traffic, connection speed and the choice of locations
"Options of the app" - тоже не сильно лучше. Можно же просто написать: 

The subscription allows you to use the app without any restrictions on traffic, connection speed, and the choice of locations.

2021-07-16 10:54 UTC, vbagirov commented on 11.vpn/030.adguard-vpn-for-ios/03.solving-problems/020.logs/docs.ru.md
> +3. В открывшейся форме введите свой Email-адрес для обратной связи и опишите найденную ошибку, включив туда время, когда эта ошибка произошла. Если воспроизвести проблему невозможно, укажите как можн
опять Email с большой, или ты специально в русском так оставил?

2021-07-16 14:12 UTC, vbagirov approved these changes

2021-07-16 14:16 UTC, merged