[Agm 975]  install/uninstall vpn for Mac
AdguardTeam/AdguardKnowledgeBase pull request #903
Opened 2021-07-19 14:43 UTC by alim-shakirov

2021-07-19 15:28 UTC, vbagirov requested changes

2021-07-19 15:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +**Объем оперативной памяти**: от 2 Гб
"Объём", ну и везде "ё" проверить

2021-07-19 15:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +**Браузеры**: Safari, Google Chrome, Opera, Yandex.Browser, Mozilla Firefox и любой другой браузер, совместимый с macOS
Это не нужно тут, мы же позиционируем наше приложение, как работающее во всех браузерах и других приложениях

2021-07-19 15:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +4. При первом запуске AdGuard VPN операционная система покажет на экране предупреждение о том, что это приложение загружено из Интернета. Нажмите *Открыть*.
по-русски "интернет" с маленькой пишется

2021-07-19 15:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +1. Откройте «Finder» и в нем перейдите в раздел «Программы».
А у Finder есть русское название?

2021-07-19 15:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +3. Нажмите на значок найденной программы и в ней в поиске введите «com.adguard.mac.vpn». Если в результатах поиска есть такая запись, удалите её.
Если дальше по тексту то, что нужно вводить с клавы, выделяем в `такой текст`, то и здесь тоже надо так сделать.

2021-07-19 15:28 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +Подробнее о AdGuard VPN для Mac вы можете узнать в [этой статье](https://kb.adguard.com/ru/vpn/adguard-vpn-mac/overview).
"об AdGuard", наверное

2021-07-19 15:37 UTC, alim-shakirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +1. Откройте «Finder» и в нем перейдите в раздел «Программы».
нет

2021-07-19 15:42 UTC, vbagirov requested changes

2021-07-19 15:42 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +1. Откройте «Finder» и в нем перейдите в раздел «Программы».
"в нём"

2021-07-19 15:42 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +Используйте эту инструкцию, если знаете, что делаете, или если служба поддержки AdGuard VPN рекомендовала вам именно *Продвинутое удаление*. Для этого сделайте следующее:
"Используйте инструкцию ..... Для этого сделайте следующее"

Получается как будто надо что-то сделать, чтобы использовать инструкцию? Надо добавить какую-то фразу в духе "Если вы хотите полностью удалить AdGuard VPN" или типа того - тут уже зависит от того, что тебе сказали в отношении продвинутого удаления разработчики

2021-07-19 15:42 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.ru.md
> +6. Нажмите *Пробел* и введите еще одну команду — `rm -f ~/Library/Group\ Containers/TC3Q7MAJXF.com.adguard.mac/Library/Preferences/TC3Q7MAJXF.com.adguard.mac.plist`.
"ещё одну"

2021-07-20 11:17 UTC, vbagirov requested changes

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +title: Установка и удаление AdGuard VPN для Mac
тайтл на ру остался

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +**RAM (Random Access Memory)**: at least 2 GB
думаю что уточнение в скобках не поможет тем, кто не знает что такое RAM =) Так что можно убрать

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +**Free disk space**: 120 Mbytes
`Mb` более общепринято, что ли

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +1. To install AdGuard VPN for Mac, just follow [this link](https://agrd.io/mac_vpn_beta) or open a browser, type *adguard-vpn.com* in the address bar and on the opened page click "Try for free".
почему ссылка на бету? У нас релиз вот-вот, давай релизную ссылку сразу зашьём

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +1. To install AdGuard VPN for Mac, just follow [this link](https://agrd.io/mac_vpn_beta) or open a browser, type *adguard-vpn.com* in the address bar and on the opened page click "Try for free".
Кстати и в ру я не обратил внимания, там тоже поправь

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +1. Open the "Finder" and go to the "Programs" section.
Finder здесь имя собственное, артикль наверное не нужен

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +2. Open the "Finder" and enter "Keychain" in the search.
тоже "the Finder"

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +2. Open the "Finder" and enter "Keychain" in the search.
везде то, что юзер вводит, выделяется `так`, а в этом пункте почему-то "так"

2021-07-20 11:17 UTC, vbagirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +4. Go back to the "Finder" and enter "Terminal" in the search.
the Finder

2021-07-20 11:30 UTC, alim-shakirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +1. To install AdGuard VPN for Mac, just follow [this link](https://agrd.io/mac_vpn_beta) or open a browser, type *adguard-vpn.com* in the address bar and on the opened page click "Try for free".
а какая ссылка тогда будет?

2021-07-20 11:34 UTC, alim-shakirov commented on 11.vpn/050.adguard-vpn-mac/020.installation/docs.en.md
> +1. To install AdGuard VPN for Mac, just follow [this link](https://agrd.io/mac_vpn_beta) or open a browser, type *adguard-vpn.com* in the address bar and on the opened page click "Try for free".
нашел

2021-07-20 13:44 UTC, vbagirov approved these changes

2021-07-20 13:51 UTC, merged