KO_KB configure system-wide blocking iOS?
AdguardTeam/AdguardKnowledgeBase pull request #908
Opened 2021-07-23 12:27 UTC by NataKiss

2021-07-23 15:27 UTC, Dariamag commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/ios_dns_protection_ko.png" style="border: 1px solid #efefef; max-width: 350px; padding: 2px;">
здесь тоже нужна max width у картинки

2021-07-26 10:49 UTC, vbagirov requested changes

2021-07-26 10:49 UTC, vbagirov commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +<img src="https://cdn.adguard.com/public/Adguard/kb/DNS_filtering/how_dns_filtering_works_ko.png" style="border: 1px solid #efefef; max-width: 350px; padding: 2px;">
Тут картинка горизонтальная, явно 350 пикселей маловато будет. Для горизонтальных картинок можно ставить 650 или 700 в ширину.

2021-07-26 10:49 UTC, vbagirov commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +### DNS 필터/호스트 파일을 추가하는 방법
Я конечно не понимаю по-корейски, но странновато, что тут есть заголовок, а перед предыдущим анкором нет. Если так задумано специально, то ок, если потерялся первый заголовок - добавь плиз

2021-07-26 10:49 UTC, vbagirov commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +1. *.iOS용 AdGuard 설정** —> **일반**
Тут звёздочка потерялась, от этого форматирование поехало, видимо

2021-07-26 10:49 UTC, vbagirov commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/ios_adding_a_filter.PNG" style="border: 1px solid #efefef; max-width: 350px; padding: 2px;">
Тут нет скрина на корейском?

2021-07-26 11:03 UTC, NataKiss commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +<img src="https://cdn.adguard.com/public/Adguard/Blog/ios_adding_a_filter.PNG" style="border: 1px solid #efefef; max-width: 350px; padding: 2px;">
добавила

2021-07-26 11:03 UTC, NataKiss commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +### DNS 필터/호스트 파일을 추가하는 방법
в анг версии заголовок тож забыли

2021-07-26 12:06 UTC, vbagirov approved these changes

2021-07-26 12:06 UTC, vbagirov commented on 05.ios/05.solving-problems/08.how-to-configure-system-wide-blocking/docs.ko.md
> +### DNS 필터/호스트 파일을 추가하는 방법
Посмотрел, англ, наверное, норм и без заголовка

2021-07-26 12:09 UTC, merged