Nata mai xiaomi1208
AdguardTeam/AdguardKnowledgeBase pull request #976
Opened 2021-11-17 08:54 UTC by nataMai

Updated instructions and screenshots for Xiaomi 12.0.8 + in English and Russian.

Closes #968

2021-11-18 11:00 UTC, vbagirov requested changes

2021-11-18 11:00 UTC, vbagirov commented on 04.android/06.solving-problems/09.background-work/docs.en.md
> +1. Go to *Settings* > *Apps* > *Manage apps* > *AdGuard*.
Сюда надо скриншот, Костя скинет. И надо явно написать "прокрутите вниз", а то могут не догадаться :)

2021-11-18 11:00 UTC, vbagirov commented on 04.android/06.solving-problems/09.background-work/docs.ru.md
> +#### MIUI 12.0.8+
Для RU все те же правки, что и для англ

2021-11-18 21:18 UTC, nataMai commented on 04.android/06.solving-problems/09.background-work/docs.en.md
> +2. *Security* app -> Tap *Gear* at the top-right corner -> *Boost speed* -> *Lock apps* -> *Lock AdGuard*
Updated accordingly.

2021-11-18 21:19 UTC, nataMai commented on 04.android/06.solving-problems/09.background-work/docs.en.md
> +Open *Security* app and tap the *Gear* icon at the top-right corner of the screen.
Updated accordingly.

2021-11-19 07:48 UTC, ameshkov approved these changes

2021-11-19 10:01 UTC, vbagirov requested changes

2021-11-19 10:01 UTC, vbagirov commented on 04.android/06.solving-problems/09.background-work/docs.ru.md
> +Зайдите в Настройки > Приложения и выберите встроенное приложение *"Безопасность"*.
"Настройки" и "Приложения" наверное надо выделить курсивом или как то

2021-11-19 10:01 UTC, vbagirov commented on 04.android/06.solving-problems/09.background-work/docs.en.md
> +Set *Battery saver* to "No restrictions".
Добавить 
"Scroll down to *Battery saver*, tap it, and set to *No restrictions*

2021-11-23 15:26 UTC, ameshkov approved these changes

2021-11-23 21:42 UTC, merged