Added info about Monterey issues
AdguardTeam/AdguardKnowledgeBase pull request #985
Opened 2021-11-29 11:37 UTC by anastasiia-fedotova

2021-11-29 13:12 UTC, sfionov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.en.md
> +You can prevent AdGuard from using the "default route" by disabling the "default route".  It can be done via Advanced Settings -> ```network.extension.monterey.force.split.tunnel```.
Здесь можно уточнить что включение этой настройки может привести к проблемам, указанным выше

2021-12-01 13:49 UTC, vbagirov requested changes

2021-12-01 13:49 UTC, vbagirov commented on 03.macos/05.solving-problems/04.big-sur-issues/docs.en.md
> +For a deeper understanding of this problem, follow the link and read [the article](https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/03.macos/05.solving-problems/07.icloud-private-relay
Эта ссылка ведёт на гитхаб, а надо давать ссылку на статью в кб: https://kb.adguard.com/en/macos/solving-problems/icloud-private-relay

2021-12-03 23:33 UTC, iOSjNaGeR approved these changes
Closed

2021-12-05 07:16 UTC, ameshkov requested changes
This way the page URL will change and we already have links to the old page.

I don't think we should change the URL at least at this moment. We can do this later when we migrate to the new KB.

2021-12-07 08:32 UTC, ameshkov approved these changes

2021-12-15 16:46 UTC, vbagirov approved these changes

2021-12-15 16:46 UTC, merged